### ISSUE TITLE
pip installing on ARM MacOS installs incorrect capstone platform

### ISSUE THREAD

**Issue by mahaloz** [angr/angr-management#1029]
### Description

If you `pip install angr-management`, then run it with `python3 -m angrmanagement` it will crash with the following error:
```python
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/mahaloz/Library/Python/3.9/lib/python/site-packages/angrmanagement/__main__.py", line 233, in <module>
    main()
  File "/Users/mahaloz/Library/Python/3.9/lib/python/site-packages/angrmanagement/__main__.py", line 226, in main
    start_management(
  File "/Users/mahaloz/Library/Python/3.9/lib/python/site-packages/angrmanagement/__main__.py", line 123, in start_management
    import angr
  File "/Users/mahaloz/Library/Python/3.9/lib/python/site-packages/angr/__init__.py", line 46, in <module>
    from .sim_procedure import SimProcedure
  File "/Users/mahaloz/Library/Python/3.9/lib/python/site-packages/angr/sim_procedure.py", line 7, in <module>
    from cle import SymbolType
  File "/Users/mahaloz/Library/Python/3.9/lib/python/site-packages/cle/__init__.py", line 11, in <module>
    from .backends import (
  File "/Users/mahaloz/Library/Python/3.9/lib/python/site-packages/cle/backends/__init__.py", line 1, in <module>
    from .backend import ALL_BACKENDS, Backend, ExceptionHandling, FunctionHint, FunctionHintSource, register_backend
  File "/Users/mahaloz/Library/Python/3.9/lib/python/site-packages/cle/backends/backend.py", line 8, in <module>
    import archinfo
  File "/Users/mahaloz/Library/Python/3.9/lib/python/site-packages/archinfo/__init__.py", line 11, in <module>
    from .arch import (
  File "/Users/mahaloz/Library/Python/3.9/lib/python/site-packages/archinfo/arch.py", line 27, in <module>
    import capstone as _capstone
  File "/Users/mahaloz/Library/Python/3.9/lib/python/site-packages/capstone/__init__.py", line 368, in <module>
    _cs = _load_lib(_path)
  File "/Users/mahaloz/Library/Python/3.9/lib/python/site-packages/capstone/__init__.py", line 341, in _load_lib
    return ctypes.cdll.LoadLibrary(lib_file)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 444, in LoadLibrary
    return self._dlltype(name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/mahaloz/Library/Python/3.9/lib/python/site-packages/capstone/lib/libcapstone.dylib, 0x0006): tried: '/Users/mahaloz/Library/Python/3.9/lib/python/site-packages/capstone/lib/libcapstone.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/mahaloz/Library/Python/3.9/lib/python/site-packages/capstone/lib/libcapstone.dylib' (no such file), '/Users/mahaloz/Library/Python/3.9/lib/python/site-packages/capstone/lib/libcapstone.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

This is the same on Python3.9 and 3.11. The error is due to libcapstone being x86 and not arm64.

### Environment

- MacOS 13.3 (22E252), Chip: Apple M2 Pro
- Latest release on PyPi 

### Additional context

For @twizmwazin:
It may also be useful to know that this normally triggers with angr-dev as well. The only way I could fix it is my compiling capstone myself and forcing the installer to use my local capstone.

**Comment by twizmwazin** [comment]
This is a problem in capstone's packaging presumably, not anything specific to angr/angr-management. It looks like capstone doesn't distribute macOS wheels at all, so presumably this was built from source. Which version does pip think is installed?

**Comment by twizmwazin** [comment]
Alright, I was able to reproduce this. 5.0.0rc4 distributes a "universal2"wheel that is actually just amd64. The best workaround is probably not installing the prerelease version at all, as the stable version (4.0.2) does not ship any macos wheels at all, and it builds and installs correctly on an apple-silicon mac. If you do want to install the prerelease version, use pip's `--no-binary` flag like this: `pip install --pre --no-binary capstone capstone`. This tells pip to skip the bad wheel and just build it from source. I know angr had issues with 5.0.0rc2 though, so its quite possible that there will also be issues with 5.0.0rc4, which came out this month and hasn't been tested with angr much yet.
