### ISSUE TITLE
Running the docker image shows ModuleNotFoundError: archr

### ISSUE THREAD

**Issue by stoeps13** [angr/angr-management#106]
When I run the latest docker build I get following error:

```
Traceback (most recent call last):                                                                                                                                                            
  File "/home/angr/angr-dev/angr-management/start.py", line 30, in <module>                                                                                                                   
    main(args.binary)                                                                                                                                                                         
  File "/home/angr/angr-dev/angr-management/angrmanagement/__main__.py", line 48, in main                                                                                                     
    from .ui.main_window import MainWindow                                                                                                                                                    
  File "/home/angr/angr-dev/angr-management/angrmanagement/ui/main_window.py", line 20, in <module>                                                                                           
    from ..data.jobs.loading import LoadTargetJob, LoadBinaryJob                                                                                                                              
  File "/home/angr/angr-dev/angr-management/angrmanagement/data/jobs/loading.py", line 1, in <module>                                                                                         
    import archr                                                                                                                                                                              
ModuleNotFoundError: No module named 'archr' 
```

Adding archr to the first `RUN` command in the Dockerfile (`pip install -e angr-management/ archr`), it works again.

**Comment by ltfish** [comment]
I think I fixed this issue before your post. See https://github.com/angr/angr-management/commit/43b65bbe708b470d07f0151941f6314c62627485.

**Comment by stoeps13** [comment]
Yes, you're right. Just built the image from the Dockerfile and it's running perfectly. Just the image on Docker Hub is 3 days old.
