### ISSUE TITLE
CFG Serialization Fails

### ISSUE THREAD

**Issue by sraboy** [angr/angr-management#107]
I just pulled in all the latest. With angr-management, my plugin subscribes to changes on `Instance.cfg_container` and immediately serializes it. I now get this exception:

```
  ERROR   | 2019-07-19 11:25:43,965 | angrmanagement.data.jobs.cfg_generation | Exception occurred in CFGGenerationJob.finish().
Traceback (most recent call last):
  File "/home/steve/code/angr-dev/angr-management/angrmanagement/data/jobs/cfg_generation.py", line 54, in finish
    inst.cfg = cfg
  File "/home/steve/code/angr-dev/angr-management/angrmanagement/data/instance.py", line 70, in cfg
    self.cfg_container.am_event()
  File "/home/steve/code/angr-dev/angr-management/angrmanagement/data/object_container.py", line 19, in am_event
    listener(**kwargs)
  File "/home/steve/code/angr-dev/angr-management/angrmanagement/plugins/chess_plugin/chess_plugin.py", line 153, in on_cfg_change
    angrcfg = self._workspace.instance.cfg.model.serialize_to_cmessage()
  File "/home/steve/code/angr-dev/angr/angr/knowledge_plugins/cfg/cfg_model.py", line 105, in serialize_to_cmessage
    memory_data.append(data.serialize_to_cmessage())
  File "/home/steve/code/angr-dev/angr/angr/knowledge_plugins/cfg/memory_data.py", line 83, in serialize_to_cmessage
    cmsg.type = _SORT_TO_IDX[self.sort]
KeyError: 'elf-header'
```

**Comment by ltfish** [comment]
Fixed in https://github.com/angr/angr/pull/1677.
