### ISSUE TITLE
AttributeError: 'PathHierarchy' object has no attribute '_successors'

### ISSUE THREAD

**Issue by ramAdam** [angr/angr-management#11]
I get this error below, when i run it . How do i fix it ? any ideas!!

python -m angrmanagement ./fauxware
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/angrmanagement/__main__.py", line 22, in <module>
    view.show()
  File "/usr/local/lib/python2.7/dist-packages/enaml/widgets/window.py", line 414, in show
    self.initialize()
  File "/usr/local/lib/python2.7/dist-packages/enaml/widgets/window.py", line 192, in initialize
    super(Window, self).initialize()
  File "/usr/local/lib/python2.7/dist-packages/enaml/widgets/toolkit_object.py", line 160, in initialize
    super(ToolkitObject, self).initialize()
  File "/usr/local/lib/python2.7/dist-packages/enaml/core/declarative.py", line 120, in initialize
    self.initialized()
  File "/usr/local/lib/python2.7/dist-packages/enaml/core/declarative_meta.py", line 68, in declarative_change_handler
    engine.write(owner, change['name'], change)
  File "/usr/local/lib/python2.7/dist-packages/enaml/core/expression_engine.py", line 210, in write
    pair.writer(owner, name, change)
  File "/usr/local/lib/python2.7/dist-packages/enaml/core/standard_handlers.py", line 82, in __call__
    call_func(func, (), {}, scope)
  File "/usr/local/lib/python2.7/dist-packages/angrmanagement/ui/main.enaml", line 103, in <module>
    inst.add_workspace(gen_symbolic_wk(inst))
  File "/usr/local/lib/python2.7/dist-packages/angrmanagement/data/instance.py", line 49, in add_workspace
    self.workspaces = self.workspaces + [wk]
  File "/usr/local/lib/python2.7/dist-packages/enaml/core/standard_tracer.py", line 55, in __call__
    engine.update(owner, self.name)
  File "/usr/local/lib/python2.7/dist-packages/enaml/core/expression_engine.py", line 241, in update
    setattr(owner, name, pair.reader(owner, name))
  File "/usr/local/lib/python2.7/dist-packages/enaml/core/looper.py", line 74, in _observe_iterable
    self.refresh_items()
  File "/usr/local/lib/python2.7/dist-packages/enaml/core/looper.py", line 129, in refresh_items
    self.parent.insert_children(self, expanded)
  File "/usr/local/lib/python2.7/dist-packages/enaml/core/object.py", line 227, in insert_children
    child_added(child)
  File "/usr/local/lib/python2.7/dist-packages/enaml/widgets/toolkit_object.py", line 182, in child_added
    super(ToolkitObject, self).child_added(child)
  File "/usr/local/lib/python2.7/dist-packages/enaml/styling.py", line 343, in child_added
    super(Stylable, self).child_added(child)
  File "/usr/local/lib/python2.7/dist-packages/enaml/core/declarative.py", line 141, in child_added
    child.initialize()
  File "/usr/local/lib/python2.7/dist-packages/enaml/widgets/toolkit_object.py", line 160, in initialize
    super(ToolkitObject, self).initialize()
  File "/usr/local/lib/python2.7/dist-packages/enaml/core/declarative.py", line 118, in initialize
    child.initialize()
  File "/usr/local/lib/python2.7/dist-packages/enaml/widgets/toolkit_object.py", line 160, in initialize
    super(ToolkitObject, self).initialize()
  File "/usr/local/lib/python2.7/dist-packages/enaml/core/declarative.py", line 118, in initialize
    child.initialize()
  File "/usr/local/lib/python2.7/dist-packages/enaml/widgets/toolkit_object.py", line 160, in initialize
    super(ToolkitObject, self).initialize()
  File "/usr/local/lib/python2.7/dist-packages/enaml/core/declarative.py", line 118, in initialize
    child.initialize()
  File "/usr/local/lib/python2.7/dist-packages/enaml/core/include.py", line 42, in initialize
    obj.initialize()
  File "/usr/local/lib/python2.7/dist-packages/enaml/widgets/toolkit_object.py", line 160, in initialize
    super(ToolkitObject, self).initialize()
  File "/usr/local/lib/python2.7/dist-packages/enaml/core/declarative.py", line 120, in initialize
    self.initialized()
  File "/usr/local/lib/python2.7/dist-packages/enaml/core/declarative_meta.py", line 68, in declarative_change_handler
    engine.write(owner, change['name'], change)
  File "/usr/local/lib/python2.7/dist-packages/enaml/core/expression_engine.py", line 210, in write
    pair.writer(owner, name, change)
  File "/usr/local/lib/python2.7/dist-packages/enaml/core/standard_handlers.py", line 82, in __call__
    call_func(func, (), {}, scope)
  File "/usr/local/lib/python2.7/dist-packages/angrmanagement/ui/pathtree.enaml", line 132, in <module>
    on_pg_sel({'value': wk.selected_pg})
  File "/usr/local/lib/python2.7/dist-packages/enaml/core/declarative_function.py", line 179, in __call__
    return _invoke(self.im_func, self.im_key, self.im_self, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/enaml/core/declarative_function.py", line 47, in _invoke
    return call_func(func, args, kwargs, scope)
  File "/usr/local/lib/python2.7/dist-packages/angrmanagement/ui/pathtree.enaml", line 148, in on_pg_sel
    pti.paths = [path for (stash, paths) in pg.stashes.items() if stash != 'pruned' for path in paths]
  File "/usr/local/lib/python2.7/dist-packages/enaml/core/standard_tracer.py", line 55, in __call__
    engine.update(owner, self.name)
  File "/usr/local/lib/python2.7/dist-packages/enaml/core/expression_engine.py", line 241, in update
    setattr(owner, name, pair.reader(owner, name))
  File "/usr/local/lib/python2.7/dist-packages/enaml/core/looper.py", line 74, in _observe_iterable
    self.refresh_items()
  File "/usr/local/lib/python2.7/dist-packages/enaml/core/looper.py", line 100, in refresh_items
    for loop_index, loop_item in enumerate(iterable):
  File "/usr/local/lib/python2.7/dist-packages/angrmanagement/ui/pathtree.enaml", line 81, in all_paths
    if path.state.se not in hierarchy._successors or len(hierarchy._successors[path.state.se]) == 0:
AttributeError: 'PathHierarchy' object has no attribute '_successors'

**Comment by rhelmot** [comment]
I get this crash too, it's not just you. @ltfish you need to fix
angr-management after all our refactors!

**Comment by ramAdam** [comment]
@rhelmot you have any workaround for it ? i had no luck opening a binary in gui

**Comment by ltfish** [comment]
Sorry, there is not a workaround for it other than fixing angr-management. I'll do it today.

**Comment by ltfish** [comment]
angr commit 07bb8cb along with angr-management commit 0ad29b8 resolves this issue.

**Comment by ramAdam** [comment]
@ltfish Thanks so much, it works
