### ISSUE TITLE
Issue at the startup

### ISSUE THREAD

**Issue by NikaFoHoWu** [angr/angr-management#12]
(angr) user@user-VirtualBox:~/angr-doc-master/examples/fauxware$ python -m angrmanagement ./fauxware
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/user/.virtualenvs/angr/lib/python2.7/site-packages/angrmanagement/__main__.py", line 4, in <module>
    from enaml.qt.qt_application import QtApplication
  File "/home/user/.virtualenvs/angr/local/lib/python2.7/site-packages/enaml/qt/**init**.py", line 35, in <module>
    raise ImportError('Cannot import PyQt4 or PySide')
ImportError: Cannot import PyQt4 or PySide

**Comment by timothyleung** [comment]
Having the same problem!

**Comment by rhelmot** [comment]
This is not an issue with angr-management. angr-management requires either PySide or PyQt4 to be installed. You have neither.

In my experience, PySide is easier to install. `pip install pyside` should suffice.

**Comment by NikaFoHoWu** [comment]
Nor PySide Nor PyQt4 installation helped

**Comment by ltfish** [comment]
What distribution of Linux are you using?

**Comment by rhelmot** [comment]
Please ensure that you can run `import pyside` in a python interpreter in the same virtualenv that angr is installed in. If it still doesn't work then, it is probably a bug in enaml.
