### ISSUE TITLE
No module named 'pyside2uic'

### ISSUE THREAD

**Issue by ShadowLL** [angr/angr-management#131]
When I installed angr-management and started with python -m angrmanagement, I got an error.
```
.virtualenvs/angr-dev/lib/python3.6/site-packages/cffi/cparser.py:164: UserWarning: Global variable 'r' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
  "(usually 'extern')" % (decl.name,))
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File ".virtualenvs/angr-dev/lib/python3.6/site-packages/angr_management-8.19.4.5-py3.6.egg/angrmanagement/__main__.py", line 66, in <module>
    main()
  File ".virtualenvs/angr-dev/lib/python3.6/site-packages/angr_management-8.19.4.5-py3.6.egg/angrmanagement/__main__.py", line 48, in main
    from .ui.main_window import MainWindow
  File ".virtualenvs/angr-dev/lib/python3.6/site-packages/angr_management-8.19.4.5-py3.6.egg/angrmanagement/ui/main_window.py", line 23, in <module>
    from .menus.help_menu import HelpMenu
  File ".virtualenvs/angr-dev/lib/python3.6/site-packages/angr_management-8.19.4.5-py3.6.egg/angrmanagement/ui/menus/help_menu.py", line 4, in <module>
    from pyside2uic.properties import QtCore
ModuleNotFoundError: No module named 'pyside2uic'
```

**Comment by rhelmot** [comment]
This was fixed in https://github.com/angr/angr-management/pull/130

**Comment by rhelmot** [comment]
it'll still fail when you install angr-management from pip until we make the next release, which might be a while because there are currently some unresolved issues elsewhere in the angr suite. You can either install everything from github, or you can backport that patch to your site-packages folder.
