### ISSUE TITLE
ImportError: cannot import name 'RegionAnnotation' from 'claripy.annotation' - when angr-management is launched

### ISSUE THREAD

**Issue by D3vil0p3r** [angr/angr-management#1360]
### Description

I built angr-management from source by using the latest git commit and I use as dependency angr latest commit.

After the install, when I launch `angr-management`, after getting the tool window logo, on terminal I get the following error:
```
Traceback (most recent call last):
  File "/usr/bin/angr-management", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/angrmanagement/__main__.py", line 231, in main
    start_management(
  File "/usr/lib/python3.12/site-packages/angrmanagement/__main__.py", line 125, in start_management
    import angr
  File "/usr/lib/python3.12/site-packages/angr/__init__.py", line 41, in <module>
    from .sim_procedure import SimProcedure
  File "/usr/lib/python3.12/site-packages/angr/sim_procedure.py", line 596, in <module>
    from angr.state_plugins.sim_action import SimActionExit
  File "/usr/lib/python3.12/site-packages/angr/state_plugins/__init__.py", line 6, in <module>
    from .posix import PosixDevFS, PosixProcFS, SimSystemPosix
  File "/usr/lib/python3.12/site-packages/angr/state_plugins/posix.py", line 7, in <module>
    from .filesystem import SimMount, Stat
  File "/usr/lib/python3.12/site-packages/angr/state_plugins/filesystem.py", line 7, in <module>
    from angr.storage.file import SimFile
  File "/usr/lib/python3.12/site-packages/angr/storage/__init__.py", line 5, in <module>
    from .file import SimFile
  File "/usr/lib/python3.12/site-packages/angr/storage/file.py", line 7, in <module>
    from .memory_mixins import DefaultMemory
  File "/usr/lib/python3.12/site-packages/angr/storage/memory_mixins/__init__.py", line 52, in <module>
    from .regioned_memory import (
  File "/usr/lib/python3.12/site-packages/angr/storage/memory_mixins/regioned_memory/__init__.py", line 3, in <module>
    from .regioned_memory_mixin import RegionedMemoryMixin
  File "/usr/lib/python3.12/site-packages/angr/storage/memory_mixins/regioned_memory/regioned_memory_mixin.py", line 8, in <module>
    from claripy.annotation import RegionAnnotation
ImportError: cannot import name 'RegionAnnotation' from 'claripy.annotation' (/usr/lib/python3.12/site-packages/claripy/annotation.py)
```

### Steps to reproduce the bug

Clone angr-management repository and build and install it by:
```
python -m build --wheel --no-isolation
python -m installer --destdir="$pkgdir" dist/*.whl
```

### Environment

Arch Linux

### Additional context

Python 3.12

**Comment by D3vil0p3r** [comment]
Solved by using the latest git version of `python-claripy`.
