### ISSUE TITLE
Fix compatibility with jupyter-client>=6

### ISSUE THREAD

**Issue by twizmwazin** [angr/angr-management#143]
Traceback when trying to run angr-management on jupyter-client==6.0.0

```
Traceback (most recent call last):
  File "start.py", line 30, in <module>
  File "angrmanagement/__main__.py", line 79, in main
  File "angrmanagement/ui/main_window.py", line 81, in __init__
  File "angrmanagement/ui/main_window.py", line 235, in _init_workspace
  File "angrmanagement/ui/workspace.py", line 50, in __init__
  File "angrmanagement/ui/views/console_view.py", line 20, in __init__
  File "angrmanagement/ui/views/console_view.py", line 64, in _init_widgets
  File "angrmanagement/ui/widgets/qipython_widget.py", line 20, in __init__
  File "site-packages/qtconsole/base_frontend_mixin.py", line 63, in kernel_client
  File "site-packages/jupyter_client/client.py", line 141, in channels_running
  File "site-packages/jupyter_client/client.py", line 200, in control_channel
TypeError: object() takes no parameters
[21549] Failed to execute script start
```

**Comment by ltfish** [comment]
It's an issue in the upstream.

Related: https://github.com/jupyter/jupyter_client/issues/523 and https://github.com/ipython/ipykernel/pull/489. We should remove the version pinning once a new version of ipykernel is released to PyPI.

**Comment by twizmwazin** [comment]
Fixed on master
