### ISSUE TITLE
Missing packages in setup.py?

### ISSUE THREAD

**Issue by joaogodinho** [angr/angr-management#15]
Hello,

Shouldn't `setup.py` include `widgets` and `utils`? Running `python -m angrmanagement` fails:

```
Traceback (most recent call last):
    File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
    File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
    File "/usr/local/lib/python2.7/dist-packages/angrmanagement/__main__.py", line 27, in <module>
        main()
    File "/usr/local/lib/python2.7/dist-packages/angrmanagement/__main__.py", line 11, in main
        from ui.main import Main
    File "/usr/local/lib/python2.7/dist-packages/enaml/core/import_hooks.py", line 143, in load_module
        exec code in mod.__dict__
    File "/usr/local/lib/python2.7/dist-packages/angrmanagement/ui/main.enaml", line 22, in
        from .state import RegistersItem, MemoryItem
    File "/usr/local/lib/python2.7/dist-packages/enaml/core/import_hooks.py", line 143, in load_module
        exec code in mod.__dict__
    File "/usr/local/lib/python2.7/dist-packages/angrmanagement/ui/state.enaml", line 8, in
        from ..widgets.api import Table
    ImportError: No module named widgets.api
```

After copying `widgets` it fails again with missing `utils`. Even after having both `widgets` and `utils`, I stil get this error:

```
Traceback (most recent call last):
    File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
    File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
    File "/usr/local/lib/python2.7/dist-packages/angrmanagement/__main__.py", line 27, in <module>
        main()
    File "/usr/local/lib/python2.7/dist-packages/angrmanagement/__main__.py", line 22, in main
        view.show()
    File "/usr/local/lib/python2.7/dist-packages/enaml/widgets/window.py", line 416, in show
        self.activate_proxy()
    File "/usr/local/lib/python2.7/dist-packages/enaml/widgets/toolkit_object.py", line 213, in activate_proxy
        child.activate_proxy()
    File "/usr/local/lib/python2.7/dist-packages/enaml/widgets/toolkit_object.py", line 213, in activate_proxy
        child.activate_proxy()
    File "/usr/local/lib/python2.7/dist-packages/enaml/widgets/toolkit_object.py", line 214, in activate_proxy
        self.activate_bottom_up()
    File "/usr/local/lib/python2.7/dist-packages/enaml/widgets/toolkit_object.py", line 236, in activate_bottom_up
        self.proxy.activate_bottom_up()
    File "/usr/local/lib/python2.7/dist-packages/enaml/qt/qt_toolkit_object.py", line 82, in activate_bottom_up
        self.init_layout()
    File "/usr/local/lib/python2.7/dist-packages/enaml/qt/qt_notebook.py", line 412, in init_layout
        self.init_selected_tab()
    File "/usr/local/lib/python2.7/dist-packages/enaml/qt/qt_notebook.py", line 453, in init_selected_tab
        if d.selected_tab:
    File "/usr/local/lib/python2.7/dist-packages/enaml/core/declarative_meta.py", line 43, in __call__
        value = engine.read(owner, name)
    File "/usr/local/lib/python2.7/dist-packages/enaml/core/expression_engine.py", line 179, in read
        return pair.reader(owner, name)
    File "/usr/local/lib/python2.7/dist-packages/enaml/core/standard_handlers.py", line 101, in __call__
        return call_func(func, (tr,), {}, scope)
    File "/usr/local/lib/python2.7/dist-packages/angrmanagement/ui/main.enaml", line 186, in <module>
        selected_tab << inst.current_workspace.name if inst.current_workspace is not None else u''
AttributeError: 'NoneType' object has no attribute 'current_workspace'
```

I'm running the latest Kali version, installed angrmanagement with `pip`.

**Comment by ltfish** [comment]
For missing packages, you are right. I'll get it fixed today.

**Comment by sverrets** [comment]
Is this still not fixed? Having the same problem as joaogodinho

**Comment by bertcug** [comment]
I got this problem too, it's still not fixed.

**Comment by bertcug** [comment]
pip install miss some files, so I cloned the code, use setup.py to install, still have the problem above.

**Comment by barbieauglend** [comment]
I am also having the same problem. Kali rolling OS.

**Comment by ltfish** [comment]
`master` branch has resolved this issue. For PyPI installs, it will be fixed when the next release comes out.

**Comment by frapik99** [comment]
Hi,
I have installed it using the ```master``` but i had the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/angr-management/angrmanagement/__main__.py", line 26, in <module>
    main()
  File "/tmp/angr-management/angrmanagement/__main__.py", line 11, in main
    from ui.main import Main
  File "/usr/local/lib/python2.7/dist-packages/enaml/core/import_hooks.py", line 143, in load_module
    exec code in mod.__dict__
  File "angrmanagement/ui/main.enaml", line 21, in 
    from .state import RegistersItem, MemoryItem
  File "/usr/local/lib/python2.7/dist-packages/enaml/core/import_hooks.py", line 143, in load_module
    exec code in mod.__dict__
  File "angrmanagement/ui/state.enaml", line 8, in 
    from ..widgets.api import Table
  File "angrmanagement/widgets/api.py", line 3, in <module>
    from .flowgraph import FlowGraph
  File "angrmanagement/widgets/flowgraph.py", line 17, in <module>
    class FlowGraph(Frame):
  File "angrmanagement/widgets/flowgraph.py", line 23, in FlowGraph
    disasm = d_(Typed(angr.analyses.Disassembly))
AttributeError: 'module' object has no attribute 'Disassembly'
```

**Comment by ltfish** [comment]
The master branch of angr-management must be used together with the master branch of other angr projects. `angr.analyses.Disassembly` is a new analysis and will be included in the next PyPI release.

**Comment by rhelmot** [comment]
This is 100% fixed for ever and always, thanks to `setuptools.find_packages`

**Comment by letoncse** [comment]
I’m using python 2.7.11 and windows 7 and getting below error. 
Traceback (most recent call last):
  File "c:\python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\src\ckan\ckan\Scripts\paster.exe\__main__.py", line 9, in <module>
  File "c:\src\ckan\ckan\lib\site-packages\paste\script\command.py", line 101, i
n run
    command = commands[command_name].load()
  File "c:\src\ckan\ckan\lib\site-packages\pkg_resources\__init__.py", line 2443
, in load
    return self.resolve()
  File "c:\src\ckan\ckan\lib\site-packages\pkg_resources\__init__.py", line 2449
, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\src\ckan\ckan\lib\cli.py", line 4, in <module>
    import os
  File "C:\src\ckan\ckan\lib\os.py", line 120, in <module>
    from os.path import (curdir, pardir, sep, pathsep, defpath, extsep, altsep,
ImportError: No module named path

How can resolve this python issue ? Thanks !

**Comment by letoncse** [comment]
> Neither angr nor angr management supports Python 2 anymore. We moved to Python 3 quite some time ago. Please use Python 3 instead.

Python 3 support CKAN on windows 7 or 10?
