### ISSUE TITLE
angrmanagement start error at "from ui.main import Main"

### ISSUE THREAD

**Issue by fr0zenrain** [angr/angr-management#17]
python -m angrmanagement
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build/bdist.macosx-10.11-x86_64/egg/angrmanagement/__main__.py", line 26, in <module>
  File "build/bdist.macosx-10.11-x86_64/egg/angrmanagement/__main__.py", line 11, in main
ImportError: No module named main

on osx 10.11 ,missing some install?,how to slove?thx!

**Comment by fr0zenrain** [comment]
it seems run 'python -m angrmanagement'  in angr-management directory running ok

**Comment by ltfish** [comment]
Hi, we just pushed a new version to GitHub, which is a complete rewritten of the old version. Can you please try the new one?

You'll have to install it from GitHub repo though.

**Comment by fr0zenrain** [comment]
test ok, good job ,thanks!

**Comment by ltfish** [comment]
No problem. Thank you for your interest in angr management. I'm closing this issue then.
