### ISSUE TITLE
QtConsole cannot show tip

### ISSUE THREAD

**Issue by ltfish** [angr/angr-management#184]
Probably because of qtpy:

```
Traceback (most recent call last):
  File "C:\Users\Fish\venvs\angr\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Fish\venvs\angr\lib\site-packages\qtconsole\frontend_widget.py", line 504, in _handle_inspect_reply
    self._call_tip_widget.show_inspect_data(content)
  File "C:\Users\Fish\venvs\angr\lib\site-packages\qtconsole\call_tip_widget.py", line 138, in show_inspect_data
    return self.show_tip(self._format_tooltip(text))
  File "C:\Users\Fish\venvs\angr\lib\site-packages\qtconsole\call_tip_widget.py", line 162, in show_tip
    screen_rect = QtWidgets.qApp.desktop().screenGeometry(text_edit)
AttributeError: module 'qtpy.QtWidgets' has no attribute 'qApp'
```

**Comment by rhelmot** [comment]
I disabled tooltips because they crash while ipdb is running.
