### ISSUE TITLE
ValueError: Can't tell my size without an arch!

### ISSUE THREAD

**Issue by flobotics** [angr/angr-management#193]
hi,
i got "angr-management nightly preview 20200811.1"  installed, when i open it, load a binary ("simple" from https://github.com/0xmilkmix/sandbox/tree/master/angr )  , then select the address 0x400785 in the "Disassembly" view, and right-click and select "Execute Symbolically".  In the "New State" pop-up, i let everything default and click "OK". Then in the "Symbolic Execution" view, i click on "explore" button, then in the "console" view, this output appears:

`Jupyter QtConsole 4.7.5
Python 3.8.5 (default, Jul 21 2020, 12:22:34) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.17.0 -- An enhanced Interactive Python. Type '?' for help.
Exception while running job "Simulation manager exploring":
Traceback (most recent call last):
  File "angrmanagement/data/instance.py", line 273, in _worker
  File "angrmanagement/data/jobs/simgr_explore.py", line 15, in run
  File "angr/sim_manager.py", line 239, in explore
  File "angr/sim_manager.py", line 261, in run
  File "angr/misc/hookset.py", line 75, in __call__
  File "angr/exploration_techniques/explorer.py", line 96, in step
  File "angr/misc/hookset.py", line 80, in __call__
  File "angr/sim_manager.py", line 346, in step
  File "angr/sim_manager.py", line 383, in step_state
  File "angr/sim_manager.py", line 422, in successors
  File "angr/factory.py", line 60, in successors
  File "angr/engines/vex/light/slicing.py", line 19, in process
  File "angr/engines/engine.py", line 149, in process
  File "angr/engines/failure.py", line 21, in process_successors
  File "angr/engines/syscall.py", line 18, in process_successors
  File "angr/engines/hook.py", line 61, in process_successors
  File "angr/engines/procedure.py", line 37, in process_procedure
  File "angr/sim_procedure.py", line 236, in execute
  File "angr/sim_procedure.py", line 384, in ret
  File "angr/calling_conventions.py", line 709, in teardown_callsite
  File "angr/calling_conventions.py", line 767, in set_return_val
  File "angr/calling_conventions.py", line 464, in return_val
  File "angr/sim_type.py", line 336, in size
ValueError: Can't tell my size without an arch!`

How can i setup arch ?

**Comment by rhelmot** [comment]
This seems to have been fixed at some point. 

![image](https://user-images.githubusercontent.com/2498805/175614701-cce8611b-7fcb-47a0-95df-edd9a5ee726b.png)
