### ISSUE TITLE
Variable recovery analysis fails when loading a previously saved angr DB

### ISSUE THREAD

**Issue by dnivra** [angr/angr-management#199]
Whenever I load a previously saved angr DB, variable recovery analysis fails. However, variable recovery runs fine when the binary is loaded for first time. Here's is traceback of one such failure:

```python
Exception while running job "Variable Recovery":
Traceback (most recent call last):
  File "/home/dnivra/angr-dev/angr-management/angrmanagement/data/instance.py", line 273, in _worker
    result = job.run(self)
  File "/home/dnivra/angr-dev/angr-management/angrmanagement/data/jobs/variable_recovery.py", line 21, in run
    inst.project.analyses.CompleteCallingConventions(
  File "/home/dnivra/angr-dev/angr/angr/analyses/analysis.py", line 115, in __call__
    oself.__init__(*args, **kwargs)
  File "/home/dnivra/angr-dev/angr/angr/analyses/complete_calling_conventions.py", line 22, in __init__
    self._analyze()
  File "/home/dnivra/angr-dev/angr/angr/analyses/complete_calling_conventions.py", line 48, in _analyze
    _ = self.project.analyses.VariableRecoveryFast(func, kb=self.kb, low_priority=self._low_priority)
  File "/home/dnivra/angr-dev/angr/angr/analyses/analysis.py", line 115, in __call__
    oself.__init__(*args, **kwargs)
  File "/home/dnivra/angr-dev/angr/angr/analyses/variable_recovery/variable_recovery_fast.py", line 225, in __init__
    raise AngrVariableRecoveryError("Function %s is empty." % repr(func))
angr.errors.AngrVariableRecoveryError: Function <Function sub_804a21d (0x804a21d)> is empty.
```

I was able to reproduce this for at least 2 binaries so it may not be binary specific. Regardless, I'm attaching the angr DB's of the two binaries I was able to observe this for. The original binaries are [CADET_00001](https://github.com/zardus/cgc-bins/blob/master/all_unpatched/CADET_00001?raw=true) and [NRFIN_00036](https://github.com/zardus/cgc-bins/blob/master/all_unpatched/NRFIN_00036?raw=true)

[angr-dbs-variable-recovery-error.zip](https://github.com/angr/angr-management/files/5758302/angr-dbs-variable-recovery-error.zip)

**Comment by ltfish** [comment]
Cannot reproduce. Might be fixed at some point. Please re-open if it still happens for you!
