### ISSUE TITLE
Error opening new exe @ macos

### ISSUE THREAD

**Issue by rmallof** [angr/angr-management#236]
Hi,

first of all, thanks for this project - it's really impressive!

While testing it in macos, I just attempted to open a random file from /usr/bin/ to try the tool, but is not able to process the file successfully:

Jupyter QtConsole 5.0.3
Python 3.8.9 (default, Apr  8 2021, 12:00:47) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.23.0 -- An enhanced Interactive Python. Type '?' for help.
Exception while running job "CFG generation":
Traceback (most recent call last):
  File "angrmanagement/data/instance.py", line 216, in _worker
  File "angrmanagement/data/jobs/cfg_generation.py", line 40, in run
  File "angr/analyses/analysis.py", line 115, in __call__
  File "angr/analyses/cfg/cfg.py", line 55, in __init__
  File "angr/analyses/cfg/cfg_fast.py", line 663, in __init__
  File "angr/analyses/forward_analysis/forward_analysis.py", line 223, in _analyze
  File "angr/analyses/cfg/cfg_fast.py", line 1234, in _post_analysis
  File "angr/analyses/cfg/cfg_base.py", line 1324, in make_functions
  File "angr/analyses/cfg/cfg_base.py", line 1559, in _process_irrational_functions
  File "angr/factory.py", line 60, in successors
  File "angr/engines/vex/light/slicing.py", line 19, in process
  File "angr/engines/engine.py", line 149, in process
  File "angr/engines/failure.py", line 21, in process_successors
  File "angr/engines/syscall.py", line 18, in process_successors
  File "angr/engines/hook.py", line 54, in process_successors
  File "angr/engines/unicorn.py", line 169, in process_successors
  File "angr/engines/soot/engine.py", line 64, in process_successors
  File "angr/engines/vex/heavy/heavy.py", line 138, in process_successors
  File "angr/engines/vex/heavy/super_fastpath.py", line 19, in handle_vex_block
  File "angr/engines/vex/light/slicing.py", line 26, in handle_vex_block
  File "angr/engines/vex/heavy/actions.py", line 30, in handle_vex_block
  File "angr/engines/vex/heavy/inspect.py", line 45, in handle_vex_block
  File "angr/engines/vex/light/light.py", line 446, in handle_vex_block
  File "angr/engines/vex/light/slicing.py", line 30, in _handle_vex_stmt
  File "angr/engines/vex/heavy/inspect.py", line 40, in _handle_vex_stmt
  File "angr/engines/vex/light/resilience.py", line 36, in inner
  File "angr/engines/vex/heavy/heavy.py", line 204, in _handle_vex_stmt
  File "angr/engines/vex/light/light.py", line 51, in _handle_vex_stmt
  File "angr/engines/vex/light/light.py", line 188, in _handle_vex_stmt_WrTmp
  File "angr/engines/vex/light/light.py", line 184, in _analyze_vex_stmt_WrTmp_data
  File "angr/engines/vex/heavy/inspect.py", line 31, in _handle_vex_expr
  File "angr/engines/vex/light/light.py", line 56, in _handle_vex_expr
  File "angr/engines/vex/heavy/actions.py", line 45, in _instrument_vex_expr
  File "angr/engines/vex/heavy/inspect.py", line 34, in _instrument_vex_expr
  File "angr/engines/vex/heavy/heavy.py", line 282, in _instrument_vex_expr
  File "angr/state_plugins/solver.py", line 864, in symbolic
AttributeError: 'NotImplementedType' object has no attribute 'symbolic'

I'm using the release from https://github.com/angr/angr-management/releases/tag/nightly-20210430.1

Thanks for your time

**Comment by rmallof** [comment]
Concretely, I used: /usr/bin/lsbom

**Comment by twizmwazin** [comment]
@rmallof I am unable to replicate, testing on macOS 10.15.7, build 20210504.1. Can you retest with that version and provide the macOS version?

**Comment by rmallof** [comment]
@twizmwazin testing with https://github.com/angr/angr-management/releases/tag/nightly-20210508.1, it keeps crashing.

I'm using macOS Big Sur 11.3

Traceback (most recent call last):
  File "angrmanagement/data/instance.py", line 216, in _worker
  File "angrmanagement/data/jobs/cfg_generation.py", line 40, in run
  File "angr/analyses/analysis.py", line 115, in __call__
  File "angr/analyses/cfg/cfg.py", line 55, in __init__
  File "angr/analyses/cfg/cfg_fast.py", line 663, in __init__
  File "angr/analyses/forward_analysis/forward_analysis.py", line 223, in _analyze
  File "angr/analyses/cfg/cfg_fast.py", line 1234, in _post_analysis
  File "angr/analyses/cfg/cfg_base.py", line 1324, in make_functions
  File "angr/analyses/cfg/cfg_base.py", line 1559, in _process_irrational_functions
  File "angr/factory.py", line 60, in successors
  File "angr/engines/vex/light/slicing.py", line 19, in process
  File "angr/engines/engine.py", line 149, in process
  File "angr/engines/failure.py", line 21, in process_successors
  File "angr/engines/syscall.py", line 18, in process_successors
  File "angr/engines/hook.py", line 54, in process_successors
  File "angr/engines/unicorn.py", line 169, in process_successors
  File "angr/engines/soot/engine.py", line 64, in process_successors
  File "angr/engines/vex/heavy/heavy.py", line 138, in process_successors
  File "angr/engines/vex/heavy/super_fastpath.py", line 19, in handle_vex_block
  File "angr/engines/vex/light/slicing.py", line 26, in handle_vex_block
  File "angr/engines/vex/heavy/actions.py", line 30, in handle_vex_block
  File "angr/engines/vex/heavy/inspect.py", line 45, in handle_vex_block
  File "angr/engines/vex/light/light.py", line 446, in handle_vex_block
  File "angr/engines/vex/light/slicing.py", line 30, in _handle_vex_stmt
  File "angr/engines/vex/heavy/inspect.py", line 40, in _handle_vex_stmt
  File "angr/engines/vex/light/resilience.py", line 36, in inner
  File "angr/engines/vex/heavy/heavy.py", line 204, in _handle_vex_stmt
  File "angr/engines/vex/light/light.py", line 51, in _handle_vex_stmt
  File "angr/engines/vex/light/light.py", line 188, in _handle_vex_stmt_WrTmp
  File "angr/engines/vex/light/light.py", line 184, in _analyze_vex_stmt_WrTmp_data
  File "angr/engines/vex/heavy/inspect.py", line 31, in _handle_vex_expr
  File "angr/engines/vex/light/light.py", line 56, in _handle_vex_expr
  File "angr/engines/vex/heavy/actions.py", line 45, in _instrument_vex_expr
  File "angr/engines/vex/heavy/inspect.py", line 34, in _instrument_vex_expr
  File "angr/engines/vex/heavy/heavy.py", line 282, in _instrument_vex_expr
  File "angr/state_plugins/solver.py", line 864, in symbolic
AttributeError: 'NotImplementedType' object has no attribute 'symbolic'

**Comment by rmallof** [comment]
I'm attaching the zipped file here for your convenience:
[lsbom.zip](https://github.com/angr/angr-management/files/6446788/lsbom.zip)

**Comment by rmallof** [comment]
@twizmwazin Hi again! I tested with the latest nightly version for macOS, this time I tried with ntoskrnl.exe and I found another crash:

Exception while running job "CFG generation":
Traceback (most recent call last):
  File "angrmanagement/data/instance.py", line 216, in _worker
  File "angrmanagement/data/jobs/cfg_generation.py", line 40, in run
  File "angr/analyses/analysis.py", line 115, in __call__
  File "angr/analyses/cfg/cfg.py", line 55, in __init__
  File "angr/analyses/cfg/cfg_fast.py", line 663, in __init__
  File "angr/analyses/forward_analysis/forward_analysis.py", line 216, in _analyze
  File "angr/analyses/forward_analysis/forward_analysis.py", line 344, in _analysis_core_baremetal
  File "angr/analyses/cfg/cfg_fast.py", line 1177, in _job_queue_empty
  File "angr/analyses/cfg/cfg_base.py", line 2447, in _process_unresolved_indirect_jumps
  File "angr/analyses/cfg/cfg_base.py", line 2473, in _process_one_indirect_jump
  File "angr/analyses/cfg/indirect_jump_resolvers/jumptable.py", line 672, in resolve
  File "angr/analyses/cfg/indirect_jump_resolvers/jumptable.py", line 737, in _resolve
  File "angr/analyses/cfg/indirect_jump_resolvers/jumptable.py", line 1176, in _jumptable_precheck
  File "angr/engines/light/engine.py", line 94, in process
  File "angr/engines/light/engine.py", line 142, in _process
  File "angr/engines/light/engine.py", line 163, in _process_Stmt
  File "angr/engines/light/engine.py", line 191, in _handle_Stmt
  File "angr/analyses/cfg/indirect_jump_resolvers/jumptable.py", line 252, in _handle_WrTmp
  File "angr/engines/light/engine.py", line 197, in _handle_WrTmp
  File "angr/engines/light/engine.py", line 229, in _expr
  File "angr/engines/light/engine.py", line 334, in _handle_Binop
  File "angr/engines/light/engine.py", line 525, in _handle_Shl
  File "claripy/operations.py", line 50, in _op
claripy.errors.ClaripyOperationError: args' length must all be equal

Thanks in advance

**Comment by rmallof** [comment]
Actually, using 20210513.1 on Windows 10 up-to-date, I got the same crash while analyzing ntoskrnl.exe:

Exception while running job "CFG generation":
Traceback (most recent call last):
  File "angrmanagement\data\instance.py", line 216, in _worker
  File "angrmanagement\data\jobs\cfg_generation.py", line 40, in run
  File "angr\analyses\analysis.py", line 115, in __call__
  File "angr\analyses\cfg\cfg.py", line 55, in __init__
  File "angr\analyses\cfg\cfg_fast.py", line 663, in __init__
  File "angr\analyses\forward_analysis\forward_analysis.py", line 216, in _analyze
  File "angr\analyses\forward_analysis\forward_analysis.py", line 344, in _analysis_core_baremetal
  File "angr\analyses\cfg\cfg_fast.py", line 1177, in _job_queue_empty
  File "angr\analyses\cfg\cfg_base.py", line 2447, in _process_unresolved_indirect_jumps
  File "angr\analyses\cfg\cfg_base.py", line 2473, in _process_one_indirect_jump
  File "angr\analyses\cfg\indirect_jump_resolvers\jumptable.py", line 672, in resolve
  File "angr\analyses\cfg\indirect_jump_resolvers\jumptable.py", line 737, in _resolve
  File "angr\analyses\cfg\indirect_jump_resolvers\jumptable.py", line 1176, in _jumptable_precheck
  File "angr\engines\light\engine.py", line 94, in process
  File "angr\engines\light\engine.py", line 142, in _process
  File "angr\engines\light\engine.py", line 163, in _process_Stmt
  File "angr\engines\light\engine.py", line 191, in _handle_Stmt
  File "angr\analyses\cfg\indirect_jump_resolvers\jumptable.py", line 252, in _handle_WrTmp
  File "angr\engines\light\engine.py", line 197, in _handle_WrTmp
  File "angr\engines\light\engine.py", line 229, in _expr
  File "angr\engines\light\engine.py", line 334, in _handle_Binop
  File "angr\engines\light\engine.py", line 525, in _handle_Shl
  File "claripy\operations.py", line 50, in _op
claripy.errors.ClaripyOperationError: args' length must all be equal

**Comment by ltfish** [comment]
This is caused by the recent overhaul of our static analysis memory model. I'll reproduce it and fix it. Thanks for reporting.

**Comment by ltfish** [comment]
Should be fixed!

**Comment by ltfish** [comment]
Well it will be fixed once we make the next angr management release, unless you have a development install.

**Comment by rmallof** [comment]
@ltfish Hi,

Thank you for the quick resolution!

 I'll check once the new version is released :)
