### ISSUE TITLE
undefined symbol: Agundirected

### ISSUE THREAD

**Issue by juneJuly** [angr/angr-management#33]
install angrmanagement success, but run python -m angrmanagement got an error:

```
WARNING | 2017-07-04 17:03:35,321 | claripy | Claripy is setting the recursion limit to 15000. If Python segfaults, I am sorry.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/angrmanagement/__main__.py", line 52, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/angrmanagement/__main__.py", line 38, in main
    from .ui.main_window import MainWindow
  File "/usr/local/lib/python2.7/dist-packages/angrmanagement/ui/main_window.py", line 13, in <module>
    from .workspace import Workspace
  File "/usr/local/lib/python2.7/dist-packages/angrmanagement/ui/workspace.py", line 7, in <module>
    from angrmanagement.ui.views import FunctionsView, DisassemblyView, SymexecView, StatesView, StringsView, ConsoleView
  File "/usr/local/lib/python2.7/dist-packages/angrmanagement/ui/views/__init__.py", line 2, in <module>
    from .disassembly_view import DisassemblyView
  File "/usr/local/lib/python2.7/dist-packages/angrmanagement/ui/views/disassembly_view.py", line 7, in <module>
    from ..widgets import QDisasmGraph, QDisasmStatusBar
  File "/usr/local/lib/python2.7/dist-packages/angrmanagement/ui/widgets/__init__.py", line 8, in <module>
    from .qpg_graph import QPathGroupGraph
  File "/usr/local/lib/python2.7/dist-packages/angrmanagement/ui/widgets/qpg_graph.py", line 2, in <module>
    import pygraphviz
  File "/usr/local/lib/python2.7/dist-packages/pygraphviz/__init__.py", line 58, in <module>
    from .agraph import AGraph, Node, Edge, Attribute, ItemAttribute, DotError
  File "/usr/local/lib/python2.7/dist-packages/pygraphviz/agraph.py", line 26, in <module>
    from . import graphviz as gv
  File "/usr/local/lib/python2.7/dist-packages/pygraphviz/graphviz.py", line 28, in <module>
    _graphviz = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/pygraphviz/graphviz.py", line 24, in swig_import_helper
    _mod = imp.load_module('_graphviz', fp, pathname, description)
ImportError: /usr/local/lib/python2.7/dist-packages/pygraphviz/_graphviz.so: undefined symbol: Agundirected
```

**Comment by juneJuly** [comment]
well, i had fixed this by :

`sudo pip install pygraphviz --install-option="--include-path=/usr/include/graphviz" --install-option="--library-path=/usr/lib/graphviz/" --upgrade --force-reinstall`

**Comment by ltfish** [comment]
It's mentioned in README.md.
