### ISSUE TITLE
Exception on console when browsing around pwn.college challenge on a fresh install.

### ISSUE THREAD

**Issue by zardus** [angr/angr-management#334]
Unfortunately, I didn't catch when exactly it was thrown. The install is 100% fresh: literally setup.sh followed by angr-management/start.py.

```
Traceback (most recent call last):
  File "/home/yans/code/angr-dev/angr-management/angrmanagement/ui/widgets/qdisasm_graph.py", line 174, in event
    self.disasm_view.keyPressEvent(event)
  File "/home/yans/code/angr-dev/angr-management/angrmanagement/ui/views/disassembly_view.py", line 216, in keyPressEvent
    self.decompile_current_function()
  File "/home/yans/code/angr-dev/angr-management/angrmanagement/ui/views/disassembly_view.py", line 421, in decompile_current_function
    self.workspace.decompile_function(self._current_function.am_obj, curr_ins=curr_ins)
  File "/home/yans/code/angr-dev/angr-management/angrmanagement/ui/workspace.py", line 315, in decompile_function
    view.function.am_event(focus=True, focus_addr=curr_ins)
  File "/home/yans/code/angr-dev/angr-management/angrmanagement/data/object_container.py", line 25, in am_event
    listener(**kwargs)
  File "/home/yans/code/angr-dev/angr-management/angrmanagement/ui/views/code_view.py", line 193, in _on_new_function
    self._focus_core(focus, focus_addr)
  File "/home/yans/code/angr-dev/angr-management/angrmanagement/ui/views/code_view.py", line 56, in _focus_core
    self.addr.am_event()
  File "/home/yans/code/angr-dev/angr-management/angrmanagement/data/object_container.py", line 25, in am_event
    listener(**kwargs)
  File "/home/yans/code/angr-dev/angr-management/angrmanagement/ui/views/code_view.py", line 146, in _on_new_addr
    block = self.workspace.instance.cfg.model.get_any_node(block_addr)
  File "/home/yans/code/angr-dev/angr-management/angrmanagement/data/object_container.py", line 60, in __getattr__
    return getattr(self._am_obj, item)
AttributeError: 'CFGModel' object has no attribute 'model'
```

**Comment by ltfish** [comment]
Apparently that part of code has not been triggered that often.
