### ISSUE TITLE
`TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'` when displaying function

### ISSUE THREAD

**Issue by zardus** [angr/angr-management#35]
Function 401aa0 causes the following exception when displayed, leading to a-m freezing up:

```Traceback (most recent call last):
  File "angrmanagement/ui/widgets/qfunction_table.py", line 120, in _on_function_selected
    self._selected(selected_item._function)
  File "angrmanagement/ui/views/functions_view.py", line 42, in _on_function_selected
    self.workspace.on_function_selected(function)
  File "angrmanagement/ui/workspace.py", line 52, in on_function_selected
    self.views_by_category['disassembly'][0].display_function(function)
  File "angrmanagement/ui/views/disassembly_view.py", line 160, in display_function
    self._display_function(function)
  File "angrmanagement/ui/views/disassembly_view.py", line 310, in _display_function
    self._flow_graph.function_graph = FunctionGraph(function=the_func)
  File "angrmanagement/ui/widgets/qdisasm_graph.py", line 104, in function_graph
    self.reload()
  File "angrmanagement/ui/widgets/qdisasm_graph.py", line 158, in reload
    self.request_relayout()
  File "angrmanagement/ui/widgets/qdisasm_graph.py", line 416, in request_relayout
    node_coords, edges = self._layout_graph()
  File "angrmanagement/ui/widgets/qdisasm_graph.py", line 406, in _layout_graph
    gl = GraphLayouter(self.function_graph.supergraph, node_sizes)
  File "angrmanagement/utils/graph_layouter.py", line 295, in __init__
    self._layout()
  File "angrmanagement/utils/graph_layouter.py", line 317, in _layout
    self._make_grids()
  File "angrmanagement/utils/graph_layouter.py", line 492, in _make_grids
    col, row = self._locations[node]
KeyError: <SuperCFGNode 0x4023d6, 1 blocks, 0 out branches>
Traceback (most recent call last):
  File "angrmanagement/ui/widgets/qdisasm_graph.py", line 311, in mousePressEvent
    block = self._get_block_by_pos(event.pos())
  File "angrmanagement/ui/widgets/qgraph.py", line 209, in _get_block_by_pos
    if b.x <= x < b.x + b.width and b.y <= y < b.y + b.height:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
Traceback (most recent call last):
  File "angrmanagement/ui/widgets/qdisasm_graph.py", line 311, in mousePressEvent
    block = self._get_block_by_pos(event.pos())
  File "angrmanagement/ui/widgets/qgraph.py", line 209, in _get_block_by_pos
    if b.x <= x < b.x + b.width and b.y <= y < b.y + b.height:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
Traceback (most recent call last):
  File "angrmanagement/ui/widgets/qdisasm_graph.py", line 311, in mousePressEvent
    block = self._get_block_by_pos(event.pos())
  File "angrmanagement/ui/widgets/qgraph.py", line 209, in _get_block_by_pos
    if b.x <= x < b.x + b.width and b.y <= y < b.y + b.height:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
```

Binary attached (it's /bin/false from the angr docker image).

**Comment by zardus** [comment]
[false.zip](https://github.com/angr/angr-management/files/1331856/false.zip)

**Comment by ltfish** [comment]
This bug is probably fixed at some point.
