### ISSUE TITLE
Decompilation view crashes when tabbing back to disassembly

### ISSUE THREAD

**Issue by mahaloz** [angr/angr-management#376]
```Traceback (most recent call last):
  File "/Users/mahaloz/github/angr-dev/angr-management/angrmanagement/ui/widgets/qccode_edit.py", line 145, in event
    return self.keyPressEvent(event)
  File "/Users/mahaloz/github/angr-dev/angr-management/angrmanagement/ui/widgets/qccode_edit.py", line 194, in keyPressEvent
    if self._code_view.keyPressEvent(event):
  File "/Users/mahaloz/github/angr-dev/angr-management/angrmanagement/ui/views/code_view.py", line 253, in keyPressEvent
    self.workspace.jump_to(self.addr.am_obj)
  File "/Users/mahaloz/github/angr-dev/angr-management/angrmanagement/ui/workspace.py", line 261, in jump_to
    view.jump_to(addr, use_animation=use_animation)
  File "/Users/mahaloz/github/angr-dev/angr-management/angrmanagement/ui/views/disassembly_view.py", line 522, in jump_to
    self._jump_to(addr, use_animation=use_animation)
  File "/Users/mahaloz/github/angr-dev/angr-management/angrmanagement/ui/views/disassembly_view.py", line 687, in _jump_to
    self.infodock.select_instruction(instr_addr, unique=True, use_animation=use_animation)
  File "/Users/mahaloz/github/angr-dev/angr-management/angrmanagement/logic/disassembly/info_dock.py", line 119, in select_instruction
    self.selected_insns.am_event(insn_addr=insn_addr)
  File "/Users/mahaloz/github/angr-dev/angr-management/angrmanagement/data/object_container.py", line 25, in am_event
    listener(**kwargs)
  File "/Users/mahaloz/github/angr-dev/angr-management/angrmanagement/plugins/trace_viewer/qtrace_viewer.py", line 299, in _on_select_ins
    positions = self.trace.get_positions(addr)
  File "/Users/mahaloz/github/angr-dev/angr-management/angrmanagement/data/object_container.py", line 60, in __getattr__
    return getattr(self._am_obj, item)
AttributeError: 'NoneType' object has no attribute 'get_positions'
```

Binary is one we use for testing, attached. 
[basic_buffer_overflows.zip](https://github.com/angr/angr-management/files/6771300/basic_buffer_overflows.zip)

**Comment by mahaloz** [comment]
Correction, this will crash when tabbing anywhere, from a bug inside the `TraceViewer` plugin.
