### ISSUE TITLE
Python crashes during CFG generation

### ISSUE THREAD

**Issue by sraboy** [angr/angr-management#59]
I've got a current git checkout on my Ubuntu box. First, is there a recommended pypy3 version that has PySide2? Mine (python 3.5.2, PyPy 5.8.0-beta0) can't find a version.

Anyway, even with CPython, angr-management crashes when I load a binary. I get a segfault after setting CFG options (no changes, left at default) for any binary:
```
(angrdev) steve@xubuntudev:~/code/angr-dev/angr-management$ ./start.py ~/code/a.out 
WARNING | 2019-02-07 08:29:33,256 | cle.loader | The main binary is a position-independent executable. It is being loaded with a base address of 0x400000.
WARNING | 2019-02-07 08:30:56,596 | cle.loader | The main binary is a position-independent executable. It is being loaded with a base address of 0x400000.
WARNING | 2019-02-07 08:30:56,842 | angr.analyses.calling_convention | Please run variable recovery on <Function _init (0x4006a0)> before analyzing its calling conventions.
WARNING | 2019-02-07 08:30:56,843 | angr.analyses.calling_convention | Cannot determine calling convention.
WARNING | 2019-02-07 08:30:56,843 | angr.analyses.calling_convention | Please run variable recovery on <Function sub_4006c0 (0x4006c0)> before analyzing its calling conventions.
WARNING | 2019-02-07 08:30:56,843 | angr.analyses.calling_convention | Cannot determine calling convention.
Segmentation fault (core dumped)
```

While tinkering, I commented out `app.exec()` in `__main__.py` and I get this:

```
(angrdev) steve@xubuntudev:~/code/angr-dev/angr-management$ ./start.py ~/code/a.out 
WARNING | 2019-02-07 07:37:42,871 | cle.loader | The main binary is a position-independent executable. It is being loaded with a base address of 0x400000.
WARNING | 2019-02-07 07:37:44,258 | cle.loader | The main binary is a position-independent executable. It is being loaded with a base address of 0x400000.
Exception in thread angr Management Worker Thread:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/steve/code/angr-dev/angr-management/angrmanagement/data/instance.py", line 178, in _worker
    result = job.run(self)
  File "/home/steve/code/angr-dev/angr-management/angrmanagement/data/jobs/cfg_generation.py", line 41, in run
    **self.cfg_args
  File "/home/steve/code/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
  File "/home/steve/code/angr-dev/angr/angr/analyses/cfg/cfg.py", line 55, in __init__
    CFGFast.__init__(self, **kwargs)
  File "/home/steve/code/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1040, in __init__
    self._analyze()
  File "/home/steve/code/angr-dev/angr/angr/analyses/forward_analysis.py", line 552, in _analyze
    self._analysis_core_baremetal()
  File "/home/steve/code/angr-dev/angr/angr/analyses/forward_analysis.py", line 677, in _analysis_core_baremetal
    self._process_job_and_get_successors(job_info)
  File "/home/steve/code/angr-dev/angr/angr/analyses/forward_analysis.py", line 695, in _process_job_and_get_successors
    successors = self._get_successors(job)
  File "/home/steve/code/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1430, in _get_successors
    jobs = self._scan_block(job)
  File "/home/steve/code/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1684, in _scan_block
    entries = self._scan_irsb(cfg_job, current_func_addr)
  File "/home/steve/code/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1871, in _scan_irsb
    stmt_idx
  File "/home/steve/code/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1968, in _create_jobs
    resolved_as_plt = self._resolve_plt(addr, irsb, ij)
  File "/home/steve/code/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 2636, in _resolve_plt
    simsucc = self.project.engines.default_engine.process(self._initial_state, irsb, force_addr=addr)
  File "/home/steve/code/angr-dev/angr/angr/engines/vex/engine.py", line 142, in process
    opt_level=opt_level)
  File "/home/steve/code/angr-dev/angr/angr/engines/engine.py", line 35, in process
    new_state = state.copy()
  File "/home/steve/code/angr-dev/angr/angr/sim_state.py", line 449, in copy
    mode=self.mode, os_name=self.os_name)
  File "/home/steve/code/angr-dev/angr/angr/sim_state.py", line 89, in __init__
    p.init_state()
  File "/home/steve/code/angr-dev/angr/angr/state_plugins/history.py", line 63, in init_state
    self.successor_ip = self.state._ip
  File "/home/steve/code/angr-dev/angr/angr/sim_state.py", line 216, in _ip
    return self.regs._ip
  File "/home/steve/code/angr-dev/angr/angr/state_plugins/view.py", line 30, in __getattr__
    return state.registers.load(k, inspect=inspect, disable_actions=disable_actions)
  File "/home/steve/code/angr-dev/angr/angr/storage/memory.py", line 796, in load
    r = r.reversed
  File "/home/steve/code/angr-dev/claripy/claripy/operations.py", line 67, in _op
    return return_type(name, fixed_args, **kwargs)
  File "/home/steve/code/angr-dev/claripy/claripy/ast/base.py", line 152, in __new__
    r = operations._handle_annotations(eb._abstract(eb.call(op, args)), args)
  File "/home/steve/code/angr-dev/claripy/claripy/backends/backend_concrete.py", line 94, in _abstract
    return BVV(e.value, e.size())
  File "/home/steve/code/angr-dev/claripy/claripy/ast/bv.py", line 251, in BVV
    try: return _bvv_cache[(value, size)]
NameError: name '_bvv_cache' is not defined
```
I can't figure this out... the way the imports are written in claripy just confuses me so I'm not sure how this global var is undefined (or getting deleted?).

EDIT: I should point out that this happens for any and every binary.

**Comment by sraboy** [comment]
The issue is happening in the async GUI stuff. I dropped to ipython right before [instance.py@179](https://github.com/angr/angr-management/blob/c97508a796500f0b6a33057a4beebb85667d44dd/angrmanagement/data/instance.py#L179).

```
(angrdev) steve@xubuntudev:~/code/angr-dev$ ./angr-management/start.py ../chess64
WARNING | 2019-02-07 09:49:23,395 | cle.loader | The main binary is a position-independent executable. It is being loaded with a base address of 0x400000.
WARNING | 2019-02-07 09:49:24,774 | cle.loader | The main binary is a position-independent executable. It is being loaded with a base address of 0x400000.
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: result                                                                                          
Out[1]: 
(<CFG Analysis Result at 0x7f8b581b49e8>,
 <CFBlanket Analysis Result at 0x7f8b49c6aba8>)

In [2]: job                                                                                             
Out[2]: Generating CFG

In [3]: job.finish()                                                                                    
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/code/angr-dev/angr-management/angrmanagement/data/instance.py in <module>
----> 1 job.finish()

TypeError: finish() missing 2 required positional arguments: 'inst' and 'result'

In [4]: job.finish(self, result)                                                                        
QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
(Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
(Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
(Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
(Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
(Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
(Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
(Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QList<QPersistentModelIndex>'
(Make sure 'QList<QPersistentModelIndex>' is registered using qRegisterMetaType().)
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread

In [5]: WARNING | 2019-02-07 09:50:03,760 | angr.analyses.calling_convention | Please run variable recovery on <Function _init (0x4006a0)> before analyzing its calling conventions.
WARNING | 2019-02-07 09:50:03,761 | angr.analyses.calling_convention | Cannot determine calling convention.
WARNING | 2019-02-07 09:50:03,761 | angr.analyses.calling_convention | Please run variable recovery on <Function sub_4006c0 (0x4006c0)> before analyzing its calling conventions.
WARNING | 2019-02-07 09:50:03,761 | angr.analyses.calling_convention | Cannot determine calling convention.
Segmentation fault (core dumped)
```

**Comment by sraboy** [comment]
The issue is VariableRecoveryFast. When I comment that out in `DisassemblyView`, everything works fine.

**Comment by sraboy** [comment]
When loading the binary in IPython, there are no crashes, though I do get errors with `VariableRecoveryFast` that I don't get with `VariableRecovery`:

```
ERROR   | 2019-02-07 11:31:39,413 | angr.analyses.variable_recovery.variable_recovery_fast.SimEngineVR | Unsupported Unop Iop_32Uto64.
ERROR   | 2019-02-07 11:31:39,414 | angr.analyses.variable_recovery.variable_recovery_fast.SimEngineVR | Unsupported Unop Iop_64to32.
ERROR   | 2019-02-07 11:31:39,414 | angr.analyses.variable_recovery.variable_recovery_fast.SimEngineVR | Unsupported Unop Iop_64to32.
ERROR   | 2019-02-07 11:31:39,414 | angr.analyses.variable_recovery.variable_recovery_fast.SimEngineVR | Unsupported Unop Iop_32Uto64.
ERROR   | 2019-02-07 11:31:39,415 | angr.analyses.variable_recovery.variable_recovery_fast.SimEngineVR | Unsupported Unop Iop_32Uto64.
WARNING | 2019-02-07 11:31:39,417 | angr.analyses.variable_recovery.variable_recovery_fast.SimEngineVR | Function handler not implemented.
```

**Comment by ltfish** [comment]
Can you provide the core dump of the crash?

**Comment by sraboy** [comment]
Sure. It's a 52MB ZIP that explodes to 1GB: https://drive.google.com/file/d/1Q0LhSKJO_p99YriNWQ6rsqXB3PFaChq4/view?usp=sharing

**Comment by sraboy** [comment]
Here's the original binary: [chess64.zip](https://github.com/angr/angr-management/files/2842235/chess64.zip)

**Comment by ltfish** [comment]
I tried the binary on angr management, and as I was expecting, it _works for me_...

Lemme analyze the coredump then.

**Comment by ltfish** [comment]
> First, is there a recommended pypy3 version that has PySide2?

As far as I know, there is no known way to get PySide2 (or even PySide) to work with PyPy. I think some people on the Internet have looked into this, and there wasn't any easy solution. Before we or someone else dedicate a lot of time to make PySide2 work with PyPy, the only way to use angr management is under CPython.

**Comment by ltfish** [comment]
@sraboy actually I have a theory. How old (or new) is your claripy install?

**Comment by ltfish** [comment]
OK, reproduced on Linux. Let me see what's going on. Thanks for reporting!

**Comment by sraboy** [comment]
@ltfish, it's the latest master (8.19.2.4). Good to hear you repro'd!

**Comment by ltfish** [comment]
I solved this crash by commenting out lline 83 - 85 in [this file](https://github.com/angr/angr/blob/master/angr/analyses/analysis.py#L83). Now I wonder why...

**Comment by sraboy** [comment]
I found that earlier too and it made no sense to me. I figured I was missing something and decided to look into the Qt and jobs code.

**Comment by sraboy** [comment]
Tinkering some more and got an interesting exception:

```
> /home/steve/code/angr-dev/angr/angr/misc/plugins.py(159)get_plugin()
-> self._provided_by_preset.append(id(plugin))
(Pdb) n
> /home/steve/code/angr-dev/angr/angr/misc/plugins.py(161)get_plugin()
-> self.register_plugin(name, plugin)
(Pdb) n
> /home/steve/code/angr-dev/angr/angr/misc/plugins.py(162)get_plugin()
-> return plugin
(Pdb) n
--Return--
> /home/steve/code/angr-dev/angr/angr/misc/plugins.py(162)get_plugin()-><angr.analyse...x7f4308068518>
-> return plugin
(Pdb) n
--Return--
> /home/steve/code/angr-dev/angr/angr/misc/plugins.py(71)__getattr__()-><angr.analyse...x7f4308068518>
-> return self.get_plugin(name)
(Pdb) n
--Call--
> /home/steve/code/angr-dev/angr/angr/analyses/analysis.py(92)__call__()
-> def __call__(self, *args, **kwargs):
(Pdb) n
> /home/steve/code/angr-dev/angr/angr/analyses/analysis.py(93)__call__()
-> fail_fast = kwargs.pop('fail_fast', False)
(Pdb) n
> /home/steve/code/angr-dev/angr/angr/analyses/analysis.py(94)__call__()
-> kb = kwargs.pop('kb', self._project.kb)
(Pdb) n
> /home/steve/code/angr-dev/angr/angr/analyses/analysis.py(95)__call__()
-> progress_callback = kwargs.pop('progress_callback', None)
(Pdb) n
> /home/steve/code/angr-dev/angr/angr/analyses/analysis.py(96)__call__()
-> show_progressbar = kwargs.pop('show_progressbar', False)
(Pdb) c
ERROR   | 2019-02-07 15:05:56,864 | angrmanagement.data.jobs.cfg_generation | Exception occurred in CFGGenerationJob.finish().
Traceback (most recent call last):
  File "angr-management/angrmanagement/data/jobs/cfg_generation.py", line 54, in finish
    super(CFGGenerationJob, self).finish(inst, result)
  File "angr-management/angrmanagement/data/jobs/job.py", line 22, in finish
    gui_thread_schedule_async(self._on_finish)
  File "angr-management/angrmanagement/logic/threads.py", line 142, in gui_thread_schedule_async
    callable()
  File "angr-management/angrmanagement/ui/workspace.py", line 73, in on_cfg_generated
    self.on_function_selected(the_func)
  File "angr-management/angrmanagement/ui/workspace.py", line 62, in on_function_selected
    self.views_by_category['disassembly'][0].display_function(function)
  File "angr-management/angrmanagement/ui/views/disassembly_view.py", line 174, in display_function
    self._display_function(function)
  File "angr-management/angrmanagement/ui/views/disassembly_view.py", line 355, in _display_function
    vr = self.workspace.instance.project.analyses.VariableRecoveryFast(the_func)
  File "/home/steve/code/angr-dev/angr/angr/analyses/analysis.py", line 114, in __call__
    oself.__init__(*args, **kwargs)
  File "/home/steve/code/angr-dev/angr/angr/analyses/variable_recovery/variable_recovery_fast.py", line 610, in __init__
    self._analyze()
  File "/home/steve/code/angr-dev/angr/angr/analyses/forward_analysis.py", line 545, in _analyze
    self._pre_analysis()
  File "/home/steve/code/angr-dev/angr/angr/analyses/variable_recovery/variable_recovery_fast.py", line 624, in _pre_analysis
    CallingConventionAnalysis.recover_calling_conventions(self.project)
  File "/home/steve/code/angr-dev/angr/angr/analyses/calling_convention.py", line 180, in recover_calling_conventions
    cc_analysis = project.analyses.CallingConvention(func)
  File "/home/steve/code/angr-dev/angr/angr/analyses/analysis.py", line 96, in __call__
    show_progressbar = kwargs.pop('show_progressbar', False)
TypeError: object.__new__(CallingConventionAnalysis): CallingConventionAnalysis is not a subtype of object
```

**Comment by ltfish** [comment]
I'm building a debugged CPython and a debugged PySide2 to debug this issue...

**Comment by ltfish** [comment]
I eventually got a debugged version setup of CPython and PySide2. This is what I got when I started angr management:

```
python3: ../Modules/gcmodule.c:380: visit_decref: Assertion `_PyGCHead_REFS(gc) != 0' failed.
Fatal Python error: Aborted

Current thread 0x00007f1462744080 (most recent call first):
  File "<frozen importlib._bootstrap_external>", line 487 in _compile_bytecode
  File "<frozen importlib._bootstrap_external>", line 779 in get_code
  File "<frozen importlib._bootstrap_external>", line 674 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "/home/fish/projects/angr-management/angrmanagement/ui/widgets/qipython_widget.py", line 2 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "/home/fish/projects/angr-management/angrmanagement/ui/views/console_view.py", line 8 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "/home/fish/projects/angr-management/angrmanagement/ui/views/__init__.py", line 7 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "/home/fish/projects/angr-management/angrmanagement/ui/workspace.py", line 13 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "/home/fish/projects/angr-management/angrmanagement/ui/main_window.py", line 15 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "/home/fish/projects/angr-management/angrmanagement/__main__.py", line 49 in main
  File "./start.py", line 28 in <module>
Aborted (core dumped)
```

Commenting out that assertion will lead angr management to fail another assertion at the location you were experiencing a crash before. If I'm not crazy, I think this has something to do with my Qt code in angr management. Let me debug it a bit.

**Comment by ltfish** [comment]
Solution:

```
pip uninstall pyside2 shiboken
pip install shiboken==5.12.0
pip install pyside2==5.12.0
```

Looks to me that PySide2 5.12.1 has an incorrect Python object reference counting somewhere. I will pin PySide2 version in angr management for now.

**Comment by sraboy** [comment]
I have the same issue with 5.12.0.

```
(angrdev) steve@xubuntudev:~/code/angr-dev$ `which python` --version
Python 3.6.7
(angrdev) steve@xubuntudev:~/code/angr-dev$ python -c "import PySide2; print(PySide2.__version__)"
5.12.0
(angrdev) steve@xubuntudev:~/code/angr-dev$ python -c "import shiboken2; print(shiboken2.__version__)"
5.12.0
```

**Comment by sraboy** [comment]
Never mind my last... it was my own debug code that broke it. I thought `git_all.sh pull` would checkout/overwrite local changes. I was wrong.

**Comment by ltfish** [comment]
So does PySide2 5.12.0 solve the problem for you as well?

**Comment by ltfish** [comment]
>  I thought `git_all.sh pull` would checkout/overwrite local changes.

We are sane people! `git_all.sh pull` works exactly the same as going into every directory and do `git pull` inside.

**Comment by sraboy** [comment]
> So does PySide2 5.12.0 solve the problem for you as well?

Yep, everything's good for me.

**Comment by ltfish** [comment]
Awesome, thanks for reporting this issue!
