### ISSUE TITLE
Exception when loading rustc compiled executable

### ISSUE THREAD

**Issue by bjorn3** [angr/angr-management#619]
```
Exception while running job "Loading file":
Traceback (most recent call last):
  File "CppHeaderParser/CppHeaderParser.py", line 2206, in __init__
  File "ply/lex.py", line 389, in token
ply.lex.LexError: Scanning error. Illegal character '$'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "angrmanagement/data/instance.py", line 284, in _worker
  File "angrmanagement/data/jobs/job.py", line 45, in run
  File "angrmanagement/data/jobs/loading.py", line 88, in _run
  File "angr/project.py", line 227, in __init__
  File "angr/project.py", line 358, in _register_object
  File "angr/procedures/definitions/__init__.py", line 327, in get
    return self.get_stub(name, arch)  # get_stub() might use the mangled name to derive the function prototype
  File "angr/procedures/definitions/__init__.py", line 345, in get_stub
    stub.prototype = self._proto_from_demangled_name(demangled_name)
  File "angr/procedures/definitions/__init__.py", line 308, in _proto_from_demangled_name
    parsed, _ = parse_cpp_file(name, with_param_names=False)
  File "angr/sim_type.py", line 2078, in parse_cpp_file
  File "CppHeaderParser/CppHeaderParser.py", line 2387, in __init__
CppHeaderParser.CppHeaderParser.CppParseError: Not able to parse  on line 1 evaluating "_"
Error around:
```

This is the executable it fails on: [cg_clif.zip](https://github.com/angr/angr-management/files/8400137/cg_clif.zip) For reference this is the `build/bin/cg_clif` file created when compiling https://github.com/bjorn3/rustc_codegen_cranelift/

**Comment by ltfish** [comment]
Thanks! Just submitted a PR.

**Comment by bjorn3** [comment]
Thanks! By the way I noticed that angr.io lists a freenode irc channel. Given what happened to freenode has it been moved somewhere else or is it still on freenode?

**Comment by ltfish** [comment]
I don't think... we have anything to do with #angr.io on freenode... @rhelmot ?

**Comment by bjorn3** [comment]
I can confirm this is now fixed.
