### ISSUE TITLE
Z3 does not work in shipped Linux bundles

### ISSUE THREAD

**Issue by bjorn3** [angr/angr-management#620]
When trying to decompile any function I get:

```
Exception while running job "Decompiling":
Traceback (most recent call last):
  File "claripy/backends/backend_z3.py", line 67, in z3_condom
  File "claripy/backends/backend_z3.py", line 373, in _abstract
  File "claripy/backends/backend_z3.py", line 407, in _abstract_internal
  File "claripy/backends/backend_z3.py", line 407, in <listcomp>
  File "claripy/backends/backend_z3.py", line 422, in _abstract_internal
  File "z3/z3core.py", line 2981, in Z3_get_numeral_string
  File "z3/z3core.py", line 1455, in Check
z3.z3types.Z3Exception: b'invalid argument'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "angrmanagement/data/instance.py", line 284, in _worker
  File "angrmanagement/data/jobs/job.py", line 45, in run
  File "angrmanagement/data/jobs/decompile_function.py", line 13, in _run
  File "angr/analyses/analysis.py", line 138, in __call__
  File "angr/analyses/analysis.py", line 122, in wrapper
  File "angr/analyses/decompiler/decompiler.py", line 48, in __init__
  File "angr/analyses/decompiler/decompiler.py", line 112, in _decompile
  File "angr/analyses/analysis.py", line 138, in __call__
  File "angr/analyses/analysis.py", line 122, in wrapper
  File "angr/analyses/decompiler/structurer.py", line 47, in __init__
  File "angr/analyses/decompiler/structurer.py", line 80, in _analyze
  File "angr/analyses/analysis.py", line 138, in __call__
  File "angr/analyses/analysis.py", line 122, in wrapper
  File "angr/analyses/decompiler/structurer.py", line 152, in __init__
  File "angr/analyses/decompiler/structurer.py", line 169, in _analyze
  File "angr/analyses/decompiler/structurer.py", line 204, in _analyze_acyclic
  File "angr/analyses/decompiler/structurer.py", line 542, in _structure_sequence
  File "angr/analyses/decompiler/structurer.py", line 589, in _merge_same_conditioned_nodes
  File "claripy/ast/base.py", line 1150, in simplify
  File "claripy/ast/base.py", line 1079, in _first_backend
  File "claripy/backends/backend_z3.py", line 67, in z3_condom
  File "claripy/backends/backend_z3.py", line 969, in simplify
  File "claripy/backends/backend_z3.py", line 69, in z3_condom
claripy.errors.ClaripyZ3Error
```

**Comment by rhelmot** [comment]
what version of z3 do you have installed? `pip freeze | grep z3-solver`

**Comment by ltfish** [comment]
There is not enough information for me to reproduce the issue. I decompiled a function in cg_clif, and this is what I got:

```
typedef struct struct_0 {
    unsigned long long field_0;
} struct_0;

extern struct_0 *_ZN7cg_clif12DEFAULT_HOOK17h961bf51847336e0cE;

int main::h0057f95d55f6e52a(long long a0, unsigned long long a0, unsigned long long a1)
{
    unsigned long v0;  // [bp-0x58]
    char v1;  // [bp-0x41]
    unsigned long long v12;  // r12
    unsigned long v13;  // r12
    struct_0 *v2;  // [bp-0x40]
    unsigned long v3;  // [bp-0x38]
    unsigned long v4;  // [bp-0x20]

    v4 = v13;
    v3 = std::time::Instant::now::h0893b711c947ae96();
    _RNvNtCs6HL397PYEi2_21rustc_data_structures9profiling21get_resident_set_size();
    _RNvCsjclYAhV18Dy_12rustc_driver21init_rustc_env_logger();
    v1 = 0;
    v2 = &_ZN7cg_clif12DEFAULT_HOOK17h961bf51847336e0cE;
    if (_ZN7cg_clif12DEFAULT_HOOK17h961bf51847336e0cE != 2)
    {
        once_cell::imp::OnceCell$LT$T$GT$::initialize::h5c512b3d358b6843(&_ZN7cg_clif12DEFAULT_HOOK17h961bf51847336e0cE, &v2);
    }
    rustc_driver::catch_with_exit_code::h0e55fb04bb4d5fc0(&v1, a0, a1);
    if (v1 != 0)
    {
        v12 = _RNvNtCs6HL397PYEi2_21rustc_data_structures9profiling21get_resident_set_size();
        std::time::Instant::elapsed::hc07a4f9cf20d5e7a();
        v0 = v12;
        _RNvNtCs6HL397PYEi2_21rustc_data_structures9profiling23print_time_passes_entry();
    }
    std::process::exit::he72b2ac8b8c7f60c();
}
```

It's ugly but it at least decompiles. Can you tell me where your angr management is from and which binary you are working on?

**Comment by ltfish** [comment]
Note to myself: We need to have a Rust demangler.

**Comment by ltfish** [comment]
> It looks like angr-management comes bundled with it's own copy of z3.

It's probably our bundle that's broken? Trying it out.

**Comment by bjorn3** [comment]
I got angr-management from the tarball at <https://github.com/angr/angr-management/releases/tag/nightly-20220331.1>. The executable I was working on is the result of compiling `fn main() {}` (which is 344k after stripping debuginfo) and then trying to decompile the `std::rt::lang_start_internal::h52e73755f77c7dd9` function. This is a rather long function. Various other functions seem to work fine now that I try it.

**Comment by bjorn3** [comment]
This is the exact executable: [rust_out.zip](https://github.com/angr/angr-management/files/8400313/rust_out.zip)

**Comment by ltfish** [comment]
Cannot reproduce on a development install on Windows. It is probably a packaging issue with our Ubuntu release? I came across a different libcairo issue when trying to run that release on my Ubuntu...

We are looking into switching to AppImage releases on Linux.

**Comment by rhelmot** [comment]
I'll try the bundled release on linux

**Comment by rhelmot** [comment]
Interestingly enough, I get a different error:

```
Traceback (most recent call last):
  File "angrmanagement/data/instance.py", line 284, in _worker
  File "angrmanagement/data/jobs/job.py", line 45, in run
  File "angrmanagement/data/jobs/decompile_function.py", line 13, in _run
  File "angr/analyses/analysis.py", line 138, in __call__
  File "angr/analyses/analysis.py", line 122, in wrapper
  File "angr/analyses/decompiler/decompiler.py", line 48, in __init__
  File "angr/analyses/decompiler/decompiler.py", line 119, in _decompile
  File "angr/analyses/analysis.py", line 138, in __call__
  File "angr/analyses/analysis.py", line 122, in wrapper
  File "angr/analyses/decompiler/structured_codegen/c.py", line 1797, in __init__
  File "angr/analyses/decompiler/structured_codegen/c.py", line 1827, in _analyze
  File "angr/analyses/decompiler/structured_codegen/c.py", line 2219, in _handle
  File "angr/analyses/decompiler/structured_codegen/c.py", line 2233, in _handle_Sequence
  File "angr/analyses/decompiler/structured_codegen/c.py", line 2219, in _handle
  File "angr/analyses/decompiler/structured_codegen/c.py", line 2272, in _handle_Condition
  File "angr/analyses/decompiler/structured_codegen/c.py", line 2219, in _handle
  File "angr/analyses/decompiler/structured_codegen/c.py", line 2233, in _handle_Sequence
  File "angr/analyses/decompiler/structured_codegen/c.py", line 2219, in _handle
  File "angr/analyses/decompiler/structured_codegen/c.py", line 2348, in _handle_AILBlock
  File "angr/analyses/decompiler/structured_codegen/c.py", line 2219, in _handle
  File "angr/analyses/decompiler/structured_codegen/c.py", line 2387, in _handle_Stmt_Assignment
  File "angr/analyses/decompiler/structured_codegen/c.py", line 2219, in _handle
  File "angr/analyses/decompiler/structured_codegen/c.py", line 2507, in _handle_Expr_Load
  File "angr/analyses/decompiler/structured_codegen/c.py", line 2161, in _deref_addr_displacement
  File "angr/analyses/decompiler/structured_codegen/c.py", line 1300, in __init__
  File "angr/analyses/decompiler/structured_codegen/c.py", line 405, in type
NotImplementedError: Class <class 'angr.analyses.decompiler.structured_codegen.c.CPlaceholder'> does not implement type().
```

I think the fact that we got to codegen means that structuring worked, which means the bug was not triggered.

@bjorn3 can you try printing out the following in the angr-management shell? I suspect that what's happening is that the python process is picking up your global z3 install, which is obviously incompatible.

```
import ctypes, gc; [x for x in gc.get_objects() if type(x) is ctypes.CDLL]
```

**Comment by bjorn3** [comment]
> I think the fact that we got to codegen means that structuring worked, which means the bug was not triggered.

The crash for me happens during "making function prototypes" I believe.

> can you try printing out the following in the angr-management shell?

It loads angr-management/z3/lib/libz3.so and not the globally installed version.

**Comment by rhelmot** [comment]
out of curiosity, are you able to do any constraint solving operation with our z3 install? try running the following in the angr-management shell:

```
import claripy
s = claripy.Solver()
a = claripy.BVS('a', 32)
s.add(a > 20)
s.add(a < 30)
s.eval(a, 1)
```

**Comment by bjorn3** [comment]
It gives the exact same invalid argument exception on `s.eval(a, 1)`.

**Comment by rhelmot** [comment]
Alright. That confirms the error is something to do with the bundled z3 or claripy and not an issue somewhere in the decompiler. This is gonna be really weird to try to track down...

What happens when you try to use the z3 package directly?

```
from z3 import *
x = Int('x')
y = Int('y')
solve(x > 2, y < 10, x + 2*y == 7)
```

**Comment by bjorn3** [comment]
Same issue...

**Comment by rhelmot** [comment]
what happens when you install z3 from pypi and do the same?

```
mkvirtualenv angr_test
workon angr_test
pip install z3-solver
python -c "from z3 import *; x = Int('x'); y = Int('y'); print(solve(x > 2, y < 10, x + 2*y == 7))"
```

**Comment by ltfish** [comment]
@rhelmot I fixed your bug on the latest angr master.

**Comment by bjorn3** [comment]
> what happens when you install z3 from pypi and do the same?

That works fine. I also tried updating to the new angr-management nightly (https://github.com/angr/angr-management/releases/tag/nightly-20220401.1) but that gives the same issue. Both trying z3 in the console and decompiling `std::rt::lang_start_internal::h52e73755f77c7dd9` give an exception.

**Comment by rhelmot** [comment]
I'm really grasping at straws here... my next guess is that somehow there are two different versions of libz3.so loaded into your process. Try running this in the console:

`[x for x in open('/proc/self/maps') if 'z3' in x]`

**Comment by bjorn3** [comment]
Indeed! It loaded both libz3.so bundled with angr-management and libz3.so.4 installed globally. Unfortunately I can't try uninstalling it as it seems the graphics driver depends on it through LLVM.

**Comment by bjorn3** [comment]
The graphics driver is probably also how the other z3 version ended up in the angr-management process.

**Comment by bjorn3** [comment]
Running without gui allows the z3 and claripy tests to work. I'm not sure how to test the decompiler.

**Comment by rhelmot** [comment]
Running without gui, as in, `./angr-management -i`?

You can run the decompiler like so:

```
[+] In [10]: p = angr.Project('/bin/true', auto_load_libs=False)
[13:24:18] [cle.loader]              |  WARNING: The main binary is a position-independent executable. It is being loaded with a base address of 0x400000.

[+] In [11]: p.analyses.CFGFast(normalize=True)
Out[11]: <CFGFast Analysis Result at 0x7fe7452587c0>

[+] In [12]: decomp = p.analyses.Decompiler(func=p.kb.functions['main'])

[+] In [13]: print(decomp.codegen.text)
```

**Comment by bjorn3** [comment]
> Running without gui, as in, ./angr-management -i?

Yes

> You can run the decompiler like so:

Thanks, will try tomorrow.

**Comment by ltfish** [comment]
What graphics driver are you using? I’m a little concerned if a graphics driver relies on Z3…

**Comment by bjorn3** [comment]
The intel graphics hd driver of mesa. Basically the dependency chain seems to be mesa -> llvm (for compiling shaders) -> z3. It seems that z3 is used by clang's static analysis tool. Distros generally don't like including the same library in multiple variants, so the same libllvm is used for clang and mesa on debian.

As for why it works on your system: On Ubuntu they disabled the z3 dependency of libllvm: https://salsa.debian.org/pkg-llvm-team/llvm-toolchain/-/blob/11/debian/rules#L81-L83

There are four solutions I can think of:

* Make it work with the system z3 version
* Rename all symbols in the bundled z3 version to avoid conflicts
* Split angr management into two processes. One containing angr itself and the other only handling the gui. Done right this may also make it more crash resistent and maybe even allow collaborative work.
* Ship a flatpak with angr management. I suspect the default runtime of flatpak has an llvm version that doesn't link to z3.

**Comment by ltfish** [comment]
Honestly this seems to be a problem with whatever Linux distro that you are using: Z3 is not used by LLVM for compiling anything. Loading libz3 by default into every GUI program is simply inviting problems, and preventing other GUI programs from using a more up-to-date Z3 library by themselves.

> Make it work with the system z3 version

Does not work. Latest Z3 has fixes that we rely on. We also sometimes upstream Z3 fixes.

> Rename all symbols in the bundled z3 version to avoid conflicts

Too much work and seems difficult to maintain in the long run.

> Split angr management into two processes.

We may split angr management into multiple processes in the future, but my last attempt failed due to excessive overhead caused by Python pickling and IPC.

> Ship a flatpak with angr management. I suspect the default runtime of flatpak has an llvm version that doesn't link to z3.

The short-term solution is AppImage. We are switching to shipping angr management under AppImage.

**Comment by bjorn3** [comment]
> Honestly this seems to be a problem with whatever Linux distro that you are using: Z3 is not used by LLVM for compiling anything.

It may break in Ubuntu too if they get ocaml support. According to the comment the reason Ubuntu doesn't enable it is because of ocaml missing in the main repo.

> Does not work. Latest Z3 has fixes that we rely on. We also sometimes upstream Z3 fixes.

Makes sense.

> Too much work and seems difficult to maintain in the long run.

I believe objcopy allows mass renaming symbols without having to edit the source code. If that is still too much work in your opinion that is understandable.

> We may split angr management into multiple processes in the future, but my last attempt failed due to excessive overhead caused by Python pickling and IPC.

I see.

> The short-term solution is AppImage. We are switching to shipping angr management under AppImage.

AppImage still uses the host graphics driver AFAIK, so that doesn't solve this issue. It can't bundle it as that would break users of nvidia's proprietary driver as well everyone with a newer graphics card than existing when bundling the AppImage. Flatpak solves this by having a runtime extension containing the graphics driver that can be updated independently of the user program.

**Comment by bjorn3** [comment]
Maybe opening the qt library with RTLD_LOCAL would avoid leaking the z3 symbols of the global z3 installation into the global symbol list of the process?

**Comment by bjorn3** [comment]
Opened https://github.com/Z3Prover/z3/issues/5941

**Comment by ltfish** [comment]
Note that angr does not really control how it loads Z3 since we use the z3-solver package on PyPI (although @rhelmot maintains that package anyway, it's probably unwise to just rewrite symbols in libz3.so shipped in that package because who knows which downstream packages that will break).

I think `RTLD_DEEPBIND` is an interesting solution. Maybe we can make it available in z3-solver as a load option? @rhelmot
