### ISSUE TITLE
Exception raised from protobuf possibly when creating a Descriptor

### ISSUE THREAD

**Issue by dnivra** [angr/angr-management#688]
On running a fresh install of current stable of angr-management, a `TypeError` is raised. This also happens with previous stable of angr-management and also current master. Full traceback:

```
Traceback (most recent call last):
  File "/home/dnivra/.virtualenvs/angr-9.2.5/bin/angr-management", line 8, in <module>
    sys.exit(main())
  File "/home/dnivra/.virtualenvs/angr-9.2.5/lib/python3.8/site-packages/angrmanagement/__main__.py", line 261, in main
    start_management(args.binary,
  File "/home/dnivra/.virtualenvs/angr-9.2.5/lib/python3.8/site-packages/angrmanagement/__main__.py", line 178, in start_management
    from .ui.css import refresh_theme  # import .ui after shwing the splash screen since it's going to take time
  File "/home/dnivra/.virtualenvs/angr-9.2.5/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/dnivra/.virtualenvs/angr-9.2.5/lib/python3.8/site-packages/angrmanagement/ui/css/__init__.py", line 6, in <module>
    from ..widgets.qccode_highlighter import reset_formats
  File "/home/dnivra/.virtualenvs/angr-9.2.5/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/dnivra/.virtualenvs/angr-9.2.5/lib/python3.8/site-packages/angrmanagement/ui/widgets/__init__.py", line 4, in <module>
    from .qdisasm_statusbar import QDisasmStatusBar
  File "/home/dnivra/.virtualenvs/angr-9.2.5/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/dnivra/.virtualenvs/angr-9.2.5/lib/python3.8/site-packages/angrmanagement/ui/widgets/qdisasm_statusbar.py", line 6, in <module>
    from angr.knowledge_plugins import Function
  File "/home/dnivra/.virtualenvs/angr-9.2.5/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/dnivra/.virtualenvs/angr-9.2.5/lib/python3.8/site-packages/angr/__init__.py", line 22, in <module>
    from .utils.formatting import setup_terminal
  File "/home/dnivra/.virtualenvs/angr-9.2.5/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/dnivra/.virtualenvs/angr-9.2.5/lib/python3.8/site-packages/angr/utils/__init__.py", line 5, in <module>
    from . import enums_conv
  File "/home/dnivra/.virtualenvs/angr-9.2.5/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/dnivra/.virtualenvs/angr-9.2.5/lib/python3.8/site-packages/angr/utils/enums_conv.py", line 6, in <module>
    from ..protos.primitives_pb2 import Edge
  File "/home/dnivra/.virtualenvs/angr-9.2.5/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/dnivra/.virtualenvs/angr-9.2.5/lib/python3.8/site-packages/angr/protos/__init__.py", line 10, in <module>
    from . import primitives_pb2
  File "/home/dnivra/.virtualenvs/angr-9.2.5/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/dnivra/.virtualenvs/angr-9.2.5/lib/python3.8/site-packages/angr/protos/primitives_pb2.py", line 32, in <module>
    _descriptor.EnumValueDescriptor(
  File "/home/dnivra/.virtualenvs/angr-9.2.5/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```

To reproduce

- Install a fresh dev version of angr-management using [angr-dev](https://github.com/angr/angr-dev) in a virtual environment. Even version 9.2.5 and 9.2.4 is sufficient.
- Run `angr-management` in the virtual environment.

**Comment by rhelmot** [comment]
Is this not fixed by https://github.com/angr/angr/pull/3364?

**Comment by dnivra** [comment]
Turns out this is a duplicate of angr/angr#3360. Since fix is being tracked on that issue, I'm closing this one.
