### ISSUE TITLE
Crash on startup from pyqodeng

### ISSUE THREAD

**Issue by mahaloz** [angr/angr-management#785]
### Description

I've been having a crash on startup for the last two weeks:
```
Traceback (most recent call last):
  File "/home/mahaloz/.virtualenvs/angr/bin/angr-management", line 8, in <module>
    sys.exit(main())
  File "/home/mahaloz/github/angr-dev/angr-management/angrmanagement/__main__.py", line 248, in main
    start_management(args.binary,
  File "/home/mahaloz/github/angr-dev/angr-management/angrmanagement/__main__.py", line 171, in start_management
    from .ui.main_window import MainWindow
  File "/home/mahaloz/github/angr-dev/angr-management/angrmanagement/ui/main_window.py", line 33, in <module>
    from ..data.instance import Instance
  File "/home/mahaloz/github/angr-dev/angr-management/angrmanagement/data/instance.py", line 29, in <module>
    from ..ui.views import DisassemblyView
  File "/home/mahaloz/github/angr-dev/angr-management/angrmanagement/ui/views/__init__.py", line 2, in <module>
    from .disassembly_view import DisassemblyView
  File "/home/mahaloz/github/angr-dev/angr-management/angrmanagement/ui/views/disassembly_view.py", line 28, in <module>
    from ..dialogs.hook import HookDialog
  File "/home/mahaloz/github/angr-dev/angr-management/angrmanagement/ui/dialogs/hook.py", line 5, in <module>
    from pyqodeng.core.modes import CaretLineHighlighterMode, PygmentsSyntaxHighlighter, AutoIndentMode
  File "/home/mahaloz/.virtualenvs/angr/lib/python3.10/site-packages/pyqodeng/core/modes/__init__.py", line 24, in <module>
    from .pygments_sh import PygmentsSH
  File "/home/mahaloz/.virtualenvs/angr/lib/python3.10/site-packages/pyqodeng/core/modes/pygments_sh.py", line 23, in <module>
    from qtpy.QtCore import QRegExp
ImportError: cannot import name 'QRegExp' from 'qtpy.QtCore' (/home/mahaloz/.virtualenvs/angr/lib/python3.10/site-packages/qtpy/QtCore.py)
```

### Steps to reproduce the bug

Run `start.py`

### Environment

- Ubuntu 22.04
- Python: 3.10
- angr: 9.2.26.dev0
- angr-management: 9.2.26.dev0
- pyqodeng: 0.0.7
- pyqodeng.core: 0.0.4

**Comment by twizmwazin** [comment]
The pyqodeng package has replaced pyqodeng.core. Try uninstalling pyqodeng.core and force-reinstalling pyqodeng.

**Comment by mahaloz** [comment]
That worked @twizmwazin, ty ty.
