### ISSUE TITLE
StringsView Broken

### ISSUE THREAD

**Issue by sraboy** [angr/angr-management#81]
Haven't had a chance to look into it yet but if you go to the strings view and change the function you're looking at and go back to "All Functions", you'll get this exception:

```
Traceback (most recent call last):
  File "/home/steve/code/angr-dev/angr-management/angrmanagement/ui/widgets/qfunction_combobox.py", line 60, in _on_current_index_changed
    self._selection_callback(function)
  File "/home/steve/code/angr-dev/angr-management/angrmanagement/ui/views/strings_view.py", line 45, in _on_function_selected
    self.reload()
  File "/home/steve/code/angr-dev/angr-management/angrmanagement/ui/views/strings_view.py", line 27, in reload
    self._string_table.function = self._selected_function
  File "/home/steve/code/angr-dev/angr-management/angrmanagement/ui/widgets/qstring_table.py", line 86, in function
    self.reload()
  File "/home/steve/code/angr-dev/angr-management/angrmanagement/ui/widgets/qstring_table.py", line 108, in reload
    for irsb_addr, _, _ in f.refs:
AttributeError: 'MemoryData' object has no attribute 'refs'
```

**Comment by ltfish** [comment]
Oops I will get it fixed.
