### ISSUE TITLE
Cannot run simulation

### ISSUE THREAD

**Issue by H-mmer** [angr/angr-management#838]
### Description

Getting this error after clicking the new simulation button.
```
Traceback (most recent call last):
  File "angrmanagement/ui/main_window.py", line 173, in open_newstate_dialog
  File "angrmanagement/ui/dialogs/new_state.py", line 81, in __init__
  File "angrmanagement/ui/dialogs/new_state.py", line 306, in _init_widgets
AttributeError: type object 'PySide6.QtCore.Qt' has no attribute 'ItemIsTristate'
```

### Steps to reproduce the bug

Arch linux, open angr-management with some binary, click new simulation.

### Environment

```
/home/hammer/.pyenv/versions/3.9.13/lib/python3.9/site-packages/angr/misc/bug_report.py:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
angr environment report
=============================
Date: 2022-12-11 21:34:15.903885
!!! running in global environment.  Are you sure? !!!
Platform: linux-x86_64
Python version: 3.9.13 (main, Jul 22 2022, 14:01:19)
[GCC 12.1.0]
######## angr #########
Python found it in /home/hammer/.pyenv/versions/3.9.13/lib/python3.9/site-packages/angr
Pip version angr 9.2.28
Couldn't find git info
######## ailment #########
Python found it in /home/hammer/.pyenv/versions/3.9.13/lib/python3.9/site-packages/ailment
Pip version ailment 9.2.28
Couldn't find git info
######## cle #########
Python found it in /home/hammer/.pyenv/versions/3.9.13/lib/python3.9/site-packages/cle
Pip version cle 9.2.28
Couldn't find git info
######## pyvex #########
Python found it in /home/hammer/.pyenv/versions/3.9.13/lib/python3.9/site-packages/pyvex
Pip version pyvex 9.2.28
Couldn't find git info
######## claripy #########
Python found it in /home/hammer/.pyenv/versions/3.9.13/lib/python3.9/site-packages/claripy
Pip version claripy 9.2.28
Couldn't find git info
######## archinfo #########
Python found it in /home/hammer/.pyenv/versions/3.9.13/lib/python3.9/site-packages/archinfo
Pip version archinfo 9.2.28
Couldn't find git info
######## z3 #########
Python found it in /home/hammer/.pyenv/versions/3.9.13/lib/python3.9/site-packages/z3
Pip version z3-solver 4.10.2.0
Couldn't find git info
######## unicorn #########
Python found it in /home/hammer/.pyenv/versions/3.9.13/lib/python3.9/site-packages/unicorn
Pip version unicorn 2.0.1.post1
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/home/hammer/.pyenv/versions/3.9.13/lib/python3.9/site-packages/angr/state_plugins/../lib/angr_native.so', handle 555919e29250 at 0x7f49194f9be0>
unicorn: <CDLL '/home/hammer/.pyenv/versions/3.9.13/lib/python3.9/site-packages/unicorn/lib/libunicorn.so.2', handle 5559197377a0 at 0x7f491e6bf6a0>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7f491f6e0e50>
z3: NOT FOUND
```

**Comment by zwimer** [comment]
@mborgerson 
The stated error message is one thing and the main point of this issue, but the env report seems odd:
1. The path is `/home/hammer/.pyenv/versions/3.9.13/lib/python3.9/site-packages/angr/misc/bug_report.py` but it says `!!! running in global environment.  Are you sure? !!!` Is this because pyenv is not considered a virtualenv but rather a choice of interpreter?
2. `z3: NOT FOUND` which itself is a bit concerning.

I'm wondering if this points to an issue in env reporting in angr; `z3` should be a hard dependency after all, no?

**Comment by twizmwazin** [comment]
That's probably an issue but its a different one from this bug report. It is most likely an issue due to not being installed inside a virtualenv.

**Comment by rhelmot** [comment]
z3: NOT FOUND has been the norm for at least a year now. Not sure what changed.
