### ISSUE TITLE
Broken function table view, error occurs when double click on function

### ISSUE THREAD

**Issue by xxr0ss** [angr/angr-management#968]
### Description

When double click a function in function table, AM won't jumpto that function, and errors occur:
```
Traceback (most recent call last):
  File "angr-dev/angr-management\angrmanagement\data\instance.py", line 133, in __getattr__
    return self.extra_containers[k]
           ~~~~~~~~~~~~~~~~~~~~~^^^
KeyError: 'on_function_selected'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "angr-dev/angr-management\angrmanagement\data\object_container.py", line 32, in am_event
    listener(**kwargs)
  File "angr-dev/angr-management\angrmanagement\ui\views\functions_view.py", line 78, in _on_function_selected
    self.instance.on_function_selected(func=func)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "angr-dev/angr-management\angrmanagement\data\instance.py", line 135, in __getattr__
    return super().__getattribute__(k)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Instance' object has no attribute 'on_function_selected'
```

### Environment

before and after commit cbc50c1217ee75a06532e5bf50fb469455006ffb

**Comment by xxr0ss** [comment]
Trying to fix this
